### ISSUE TITLE
换了个这个主题，首页的 tags 和 about 直接就404了

### ISSUE THREAD

**Issue by yangg** [ahonn/hexo-theme-even#10]
新配置的 hexo

**Comment by ahonn** [comment]
查看文档 [标签页与关于页](https://github.com/ahonn/hexo-theme-even/blob/master/doc/doc_zh.md#%E6%A0%87%E7%AD%BE%E9%A1%B5)

**Comment by yangg** [comment]
tag 页的数量是不是有问题，比实际多一个

**Comment by ahonn** [comment]
啊？什么意思？发个图看看
On May 28, 2016, at 14:16, Brook <notifications@github.com<mailto:notifications@github.com>> wrote:


tag 页的数量是不是有问题，比实际多一个

**Comment by yangg** [comment]
![](http://ww3.sinaimg.cn/large/006tNbRwgw1f4b2sz5q6wj30gy0fz75z)

**Comment by ahonn** [comment]
哎，woc。真的是，我没去数过..马上修

**Comment by yangg** [comment]
好的，谢谢
还有个小问题，副标题设置成中文，结果导航就成中文了，这是 feature 么？

**Comment by ahonn** [comment]
导航栏的语言是根据  `yoursite/_config.yml` 中的 `language` 设置有关的。
你可以在 `yoursite/themes/even/languages/` 中修改 `en.yml` 或 `zh-cn.yml` 文件。
也可以在这个目录下面新建其他 yml，然后只要在 `yoursite/_config.yml` 中的 `language` 设置对应的文件名就可以了。

**Comment by yangg** [comment]
你好，按你现在的doc 我要修改social那些需要根本主题下的配置文件，那我得fork一下你的项目？

**Comment by ahonn** [comment]
even 主题的目录下不就有 _configyml 嘛
On May 28, 2016, at 15:10, Brook <notifications@github.com<mailto:notifications@github.com>> wrote:


你好，按你现在的doc 我要修改social那些需要根本主题下的配置文件，那我得fork一下你的项目？

**Comment by yangg** [comment]
好吧

不知道没有考虑去掉引用的两个字体
我这里bootcss 加载好慢，不知道有没有考虑去掉这个 fontawesome（貌似只用了4个图标）
后面那个字体好像也没用到
