### ISSUE TITLE
侧边栏目录无法固定？

### ISSUE THREAD

**Issue by ormsf** [ahonn/hexo-theme-even#100]
请问博主，看到您的博客中文章的侧边栏的目录在鼠标滚动的时候，目录会一直固定不动，请问要怎么设置才能出现这种效果？

**Comment by ahonn** [comment]
不用设置啊，本来就有得

**Comment by ormsf** [comment]
@ahonn 不知道我设置了什么，现在目录不会固定不动，请问博主我现在应该怎么设置才能回到原来固定不动的效果？

**Comment by ahonn** [comment]
…. 并没有固定不动的设置.. 原先不动是因为 JavaScript 没有加载完..

On 30 January 2017 at 15:10:37, ormsf (notifications@github.com<mailto:notifications@github.com>) wrote:

@ahonn<https://github.com/ahonn> 不知道我设置了什么，现在目录不会固定不动，请问博主我现在应该怎么设置才能回到原来固定不动的效果？

**Comment by ormsf** [comment]
@ahonn 那现在的话，如果我想要内容滚动的时候，目录固定到不动的话应该怎么重新设置回来，是不是只能重新git clone主题？

**Comment by ahonn** [comment]
… 网速慢才会那样.. 主题本身并没有这种功能..

如果你需要固定文章目录的话，可以注释掉这行 https://github.com/ahonn/hexo-theme-even/blob/master/source/js/src/bootstrap.js#L5



On 30 January 2017 at 15:23:49, ormsf (notifications@github.com<mailto:notifications@github.com>) wrote:

@ahonn<https://github.com/ahonn> 那现在的话，如果我想要内容滚动的时候，目录固定到不动的话应该怎么重新设置回来，是不是只能重新git clone主题？

**Comment by ormsf** [comment]
@ahonn 也没有效果，我在查一查是不是改动了其他的设置，谢谢回复。
