### ISSUE TITLE
在配置文件URL设置了root之后,搜索组件无法搜索

### ISSUE THREAD

**Issue by skyline-123** [ahonn/hexo-theme-even#103]
你好,首先感谢你精心设计的even主题,我非常喜欢并在自己的博客项目中使用了它.
最近我发现搜索组件无法使用,调试之后发现是自己设置了root路径的原因.刚开始使用默认的路径,但是由于项目原因,我将hexo生成的文件放在自己服务器的blog文件夹下,更改了url的root为/blog.设置之后发现无法搜索.不知道有没有办法解决这个问题?

**Comment by skyline-123** [comment]
_fetchSearchData: function () {
      var searchPath = '/blog/search.xml';  

已经找到方法了,修改了下具体js文件下的路径,就解决问题了.建议在wiki添加提醒.

**Comment by ahonn** [comment]
你好。抱歉，这个是由于我没有考虑周全所产生的 Bug。

搜索文件的路径是根据 header 中的 themeConig 变量设置的。直接写死不是很好，我正在着手修改。待会会 push 上来。

你可以直接将 `layout/_script/config.swig` 修改为：

``` swig
{% set searchPath = config.search.path || 'search.xml' %}
{% set themeConfig = theme.theme %}
<script type="text/javascript">
  var themeConfig = {
    search: {
      enable: {{themeConfig.search}},
      path: "{{url_for(searchPath)}}",  // <- This line
    },
   // ....
</script>
```
