### ISSUE TITLE
markdown 表格无效

### ISSUE THREAD

**Issue by luckyBears** [ahonn/hexo-theme-even#109]
markdown 表格无效

**Comment by ahonn** [comment]
你好。我测试了一下，表格并无问题。请确保你的 markdown 表格书写正确，我在你博客上拷贝的表格无法显示。

```
| :———–: | :—–: | :–: | :–: | :–: | :—: |
```

目测是这个横线是错的，应该是这样。

```
| :------: | :-----: | :--: | :--: | :--: | :---: |
```

**Comment by luckyBears** [comment]
---
#测试一下表格
| 姓名 | 年龄 | 班级 |
| ---- | ---- | ----- |
| 张三 | 4 | 一班 |

| 姓名     |  年领   | 班级 | 学校|小组|成绩|
| :------: | :-----: | :--: | :--: | :--: | :---: |
|收费|发生地方|第三方|地噶说|的方式|地方|

上面那个是我写的，下面那个是复制你的。我想知道我们两个的-有什么不同吗?我的渲染不出效果，你的可以。但是放到CMD Markdown 等三方编辑器中可以正常显示。| : -全部是英文下输入的

**Comment by ahonn** [comment]
明显你的横线与我的不同。

你的： `———–`
正确的：`-------`

我将你博客上面显示不出来的 markdown 表格放到第三方编辑器（Quiver）中同样无法显示。

**Comment by luckyBears** [comment]
我在找着原因吧

**Comment by ahonn** [comment]
你可以看到你回复我的两个表格第一个显示不出来。在博客上的 markdown 表格之前是否有空行？

**Comment by luckyBears** [comment]
改好了，但是渲染的效果差强人意啊。表格没有缩进，太丑了。用的是hexo-renderer-marked来渲染的。
