### ISSUE TITLE
你好，Stackoverflow怎么加进去？

### ISSUE THREAD

**Issue by wenzhishen** [ahonn/hexo-theme-even#11]
你的主题挺好看的，想问一下怎么添加StackOverflow

**Comment by ahonn** [comment]
<img width="318" alt="screen shot 2016-06-12 at 21 38 07" src="https://cloud.githubusercontent.com/assets/9718515/15991462/fa0e69e4-30e5-11e6-9680-27c4d59cf5eb.png">
不会很奇怪吗.. 当初是有加的

**Comment by ahonn** [comment]
我把 StackOverflow 加上了。

修改图标的方法：
- 在 [iconfont](http://iconfont.cn/) 上选择需要的图标，添加并创建项目
- 下载后解压重命名为 `iconfont`
- 覆盖原主题 `source/fonts/iconfont` 
- 在 `source/fonts/iconfont/iconfont.css` 修改图标大小，位置的 Style

（这样无法保留原有的图标..暂时没有好的解决办法..只能慢慢把主题的图标补全了）
