### ISSUE TITLE
知识版权协议点击后非外部链接方式打开

### ISSUE THREAD

**Issue by quentin-chen** [ahonn/hexo-theme-even#112]
现在的知识版权协议点击时，是在当前页面打开的。

应该和文章内插入的外部链接一样，在新页面中打开才对。

**Comment by quentin-chen** [comment]
This is the normal external link inserted to the post.

```html
<a href="https://www.cyberciti.biz/faq/rhel-fedorta-linux-iptables-firewall-configuration-tutorial/" target="_blank" rel="external">相关资料</a>
```

This is the copyright license link:

```html
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>
```

**Comment by ahonn** [comment]
这部分可以在主题配置文件[自定义](https://github.com/ahonn/hexo-theme-even/wiki/%E8%AE%BE%E7%BD%AE%E6%96%87%E7%AB%A0%E7%89%88%E6%9D%83%E4%BF%A1%E6%81%AF)

我会把默认的修改成新标签打开 : )

**Comment by quentin-chen** [comment]
咦，我没有注意到……捂脸
