### ISSUE TITLE
主页文章预览添加空行

### ISSUE THREAD

**Issue by dbarobin** [ahonn/hexo-theme-even#113]
你好，我想在主页文章预览添加空行，请问应该修改哪个文件？

![index](https://cloud.githubusercontent.com/assets/3949252/23244653/cc6f7f3c-f9c1-11e6-887d-53002490fdf4.png)

对应上图，具体需求是在 **2017 年 2 月 22 日** 之后和 **阅读更多** 之前添加空行。

感谢！

**Comment by ahonn** [comment]
这个本来就是有的啊。讲道理这段文字的上下都说会有外边距的。

浏览器查看一下样式，我看不到你的页面不知道是什么情况。

**Comment by dbarobin** [comment]
我没有用文章截断（）的方式，而是用的 description 字段，是否是这个问题？

**Comment by dbarobin** [comment]
我测试了下，果然 \<\!\-\- more \-\-\> 有空行，description 字段没有，麻烦将两种方式保持相同的样式，谢谢了。

**Comment by quentin-chen** [comment]
@ahonn 室友天天「讲道理」，看到你说「讲道理」，一阵莫名的喜感……

**Comment by ahonn** [comment]
@dbarobin 已修复～

**Comment by ahonn** [comment]
@quentin-chen 有时候 “讲道理” 还是很顺口的～

**Comment by dbarobin** [comment]
@ahonn 好的，辛苦了，非常感谢哈
