### ISSUE TITLE
主页 GitHub 图标链接异常

### ISSUE THREAD

**Issue by dbarobin** [ahonn/hexo-theme-even#114]
我的域名是：[http://blog.xxxx.com](http://blog.xxxx.com)，CNAME 对应 blog.xxxx.com。

_config.yml 中的 github 设置为 GitHub 用户名，但点击 GitHub 图标，链接为 http://blog.xxxx.com/xxxx

求解，感谢！

**Comment by ahonn** [comment]
参考我的配置 https://github.com/ahonn/hexo-theme-even/blob/ahonn/_config.yml

社交链接是直接点地址，若不是的话会直接跳到博客的相对路径

**Comment by dbarobin** [comment]
理解成配置 GitHub 用户名了，原来是完整链接，哈哈哈。感谢哈。
