### ISSUE TITLE
添加下一篇，

### ISSUE THREAD

**Issue by wangleah** [ahonn/hexo-theme-even#116]
请问如何添加下一篇，还有点击搜索总是跳转一个广告页面

**Comment by ahonn** [comment]
请描述详细一点，没懂你的意思

**Comment by wangleah** [comment]
下载了主题，没有上一页下一页


发自网易邮箱大师
在2017年03月05日 18:43，Yuexun Jiang 写道：

请描述详细一点，没懂你的意思

**Comment by ahonn** [comment]
依旧没有描述清楚，可以适当添加图片说明吗
