### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by maquannene** [ahonn/hexo-theme-even#12]
我用不同的电脑看，字体是不一样的，有没有什么办法统一字体。

**Comment by ahonn** [comment]
具体是哪个位置的字体呢..现在没 Windows 系统，不知道具体是什么样。要统一字体的话就得把字体都内置了，全放 fonts 下。

**Comment by maquannene** [comment]
全文的字体。我发现我用我的 mbp 打开是一种字体，然后我用 mac mini 打开又是另外一种字体。
我想应该是和 os 自带的字体有关系。能不能统一成一种字体，就是每个 os 打开显示的都一样。

**Comment by ahonn** [comment]
找个字体内置进主题的话就可以。不过觉得没有这样做的必要啊.. 全文的字体讲道理差别应该不会很大。

**Comment by maquannene** [comment]
好吧。那算了，不搞了。
我有另外一个问题：每一级的标题前面为什么会带个 # ，能否去除。
还有，什么时候考虑侧面集成一个mini 目录，就是滚动博客的时候，目录响应条目会高亮。

**Comment by ahonn** [comment]
好像大家都不喜欢那个 # 锚点..我把它去掉好了。

目录那个我之前尝试过加侧边栏里面，发现不是很好看就去掉了。
后面就打算文章侧边加，还在 ToDo 中。之后会加。

感谢反馈 ：）

**Comment by maquannene** [comment]
ok  thx so much
