### ISSUE TITLE
Unable to show long TOC content

### ISSUE THREAD

**Issue by weihanglo** [ahonn/hexo-theme-even#120]
If the TOC contains too many items. The content navigator cannot show the overflow part as below: 

<img width="500" alt="screen shot 2017-03-10 at 18 03 34" src="https://cloud.githubusercontent.com/assets/14314532/23790894/f2e25e2c-05bb-11e7-8267-35b1bdd6b029.png">

Maybe we should add scrollbar into content navigator, or let the current item auto-scroll to visible area?

Thanks!

**Comment by ahonn** [comment]
I will add scrollbar into TOC. But I don't think the TOC should have such a long. Divided into a few articles will be better, I think.

Anyway, Thank you for your advice.

**Comment by weihanglo** [comment]
Nice work!
 
Thanks a lot.
