### ISSUE TITLE
添加代码模块语言支持

### ISSUE THREAD

**Issue by zhanghedr** [ahonn/hexo-theme-even#122]
目前我用Typora写markdown代码模块时可以用sql、http等代码高亮，hexo主题里sql模块会高亮但是语言无法分辨显示CODE如下：
![image](https://cloud.githubusercontent.com/assets/12772284/23886035/07a8758c-084e-11e7-97e4-b83acc3851e1.png)

然后http不会高亮，能不能像github这样：
``` http
POST /v1/people HTTP/1.1
Host: api.example.com
Content-Type: application/json
Accept: application/json
 
{
  "username": "zhanghedr",
  "email": "example@gmail.com",
  "bio": "Software Engineer"
}
```
能不能增加一些常用语言高亮和分辨的支持，谢谢了

**Comment by ahonn** [comment]
添加了 SQL 与 HTTP，但是由于 Hexo 自带的高亮没有解析 HTTP，所以你可能需要安装其他插件来实现。

**Comment by zhanghedr** [comment]
谢谢
