### ISSUE TITLE
如何更改主页 Title 字体大小

### ISSUE THREAD

**Issue by dbarobin** [ahonn/hexo-theme-even#125]
如题，Thanks!

**Comment by dbarobin** [comment]
采用的语言是中文。

**Comment by ahonn** [comment]
可以在 `source/css/_custom/_custom.scss` 中进行样式覆盖，从而自定义主题样式。

主页 Title 是指左上角？可以通过在 _custom.scss 添加 [$logo-font-size](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss#L94) 自定义，其他样式也是如此。

**Comment by dbarobin** [comment]
感谢！
