### ISSUE TITLE
关于主题更新的问题

### ISSUE THREAD

**Issue by buginux** [ahonn/hexo-theme-even#126]
我发现目前这个主题的更新还是很频繁的。不知各位是怎样保持主题更新的，我现在的方式是自己 fork 了一份，然后使用 upstream 来跟踪上游的原仓库，然后定期去更新上游然后再我自己的合并。

这种做法的问题在于有时候如果长时期没更新，变动很大，容易出现冲突，解决起来比较麻烦，挺费时间的。

不知道博主是否有更方便的方式，烦请告知下。

**Comment by ahonn** [comment]
这个真没啥好办法。或许搞一个迁移工具？

目前应该趋于稳定了，应该不会有什么大更新。
