### ISSUE TITLE
搜索hexo-generator-search不工作

### ISSUE THREAD

**Issue by zhanghedr** [ahonn/hexo-theme-even#132]
安装了`npm install hexo-generator-search --save` "hexo-generator-search": "^1.0.4"，在根目录_config.yml添加了
``` yml
search:
  path: search.xml
  field: post
```
在theme的_config.yml也enable了search，但搜索时typeahead出错：
``` js
Uncaught TypeError: Cannot read property 'filter' of null
    at HTMLInputElement.handleSearchInput (search.js?v=2.3.x:52)
    at HTMLInputElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLInputElement.q.handle (jquery-3.1.1.min.js:3)
```
就是这一行：
``` js
var searchResult = _searchData.filter(function (item) {
```
想问下是我有东西没设置好还是bug，谢谢

**Comment by ahonn** [comment]
看起来是 http://www.zhanghedr.com/2017/03/12/rest-and-soap/ 这篇文章的问题，生成的用于搜索的 XML 格式错误，具体见：http://www.zhanghedr.com/search.xml

这可能是插件的 Bug，移除这篇文章之后再试试看？

**Comment by zhanghedr** [comment]
确实是这篇文章encoding问题，谢谢
