### ISSUE TITLE
友链问题

### ISSUE THREAD

**Issue by gloxec** [ahonn/hexo-theme-even#133]
这个如何添加友链呢？

**Comment by ahonn** [comment]
没有提供友链功能，可以参照 [添加自定义页面](https://github.com/ahonn/hexo-theme-even/wiki/%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2) 添加单独的一页为友链。

效果：https://www.ileyar.com/links/

**Comment by gloxec** [comment]
好吧，已经实现了。
问下大佬以后会不会增加友链的功能，和外部文章tags标签标注的功能呢？
