### ISSUE TITLE
数学公式和事件列表

### ISSUE THREAD

**Issue by plmsmile** [ahonn/hexo-theme-even#135]
你好，我有2个问题。
问题1：我在md里面加入了数学公式，但是网页上却显示是源代码。
问题2：在md里面写了事件列表，网页上也是显示源代码。

**Comment by ahonn** [comment]
抱歉，最近忙着面试，没时间解决 Issue。

- 数学公式的话可以通过 Hexo 插件添加，见 [#41](https://github.com/ahonn/hexo-theme-even/issues/41)。正在考虑添加到主题中。
- 关于事件列表（ToDo List）可查看 [hexo-renderer-marked #30](https://github.com/hexojs/hexo-renderer-marked/issues/30)。更新 hexo-renderer-marked 至 0.3.0 即可。
