### ISSUE TITLE
博客首页每篇都是全部显示

### ISSUE THREAD

**Issue by jiangtianyou** [ahonn/hexo-theme-even#136]
请教一下，博客每篇都是全篇显示，不是显示部分的形式，没有readmore，这个可能会是什么原因？
这是网址https://jiangtianyou.github.io/

**Comment by ahonn** [comment]
[添加首页文章阅读全文](https://github.com/ahonn/hexo-theme-even/wiki/%E6%B7%BB%E5%8A%A0%E9%A6%96%E9%A1%B5%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E5%85%A8%E6%96%87)
