### ISSUE TITLE
代码块语法支持

### ISSUE THREAD

**Issue by inkydragon** [ahonn/hexo-theme-even#137]
**代码块语法支持不完全**

md源码 [test.md](https://gist.github.com/inkydragon/247dea86ec79d9d100faf930527fc515)

even主题生成效果 [Hexo 测试页](http://inkydragon.github.io/PublishTime-test/)

可以看出even主题对代码块语法支持不完全

![20170422220113](https://cloud.githubusercontent.com/assets/5158738/25305066/3e9069ec-27a7-11e7-9c8c-2be7a236bdbc.png)

------

代码块语法 及 正常情况 参见
hexo-doc [代码块](https://hexo.io/zh-cn/docs/tag-plugins.html#代码块)
```
附加说明和网址
{% codeblock _.compact http://underscorejs.org/#compact Underscore.js %}
_.compact([0, 1, false, 2, '', 3]);
=> [1, 2, 3]
{% endcodeblock %}

反引号代码块

``` [language] [title] [url] [link text] code snippet ```
```

> node.js hexo even均为最新版 (今天全删了重装 ，换主题
>
> I:\GitHub\inkydragon.github.io\hexo>hexo -v
hexo: 3.3.1
hexo-cli: 1.0.2
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j

**Comment by ahonn** [comment]
已 fix。效果如下图：

![](http://ww3.sinaimg.cn/large/006tNc79gy1fewtqdyzi8j30ml0itq4m.jpg)

虽然已经修复了这个问题，但是不建议在博客中使用。

这是 Hexo 添加的 Tag 而非标准的 Markdown 语法。若以后迁移博客可能会有问题，其他标签插件功能也相同不建议使用。
