### ISSUE TITLE
超长TOC滚动

### ISSUE THREAD

**Issue by inkydragon** [ahonn/hexo-theme-even#138]
在目录超长时，滚动文章内容，TOC会出现滑条，其中有一段当前标题是隐藏状态

应该让TOC自动滚动目录让其显示，也可考虑取消滑条更美观。

测试页面  [超长 TOC 滚动](http://inkydragon.github.io/hexo-test/#———-Day-3-———)

**Comment by lovemegowin** [comment]
你好 我也遇到这个问题了 能问下你是怎么解决的不？

**Comment by inkydragon** [comment]
@lovemegowin 因为影响不是很大，我自己就没有研究怎么改进了。如果你想该可以试试从CSS空去掉滑条，TOC自动滚动可能需要上js。不是很了解前端就只能给一点方向了。

**Comment by lovemegowin** [comment]
@inkydragon  嗯嗯好的 多谢了 我抽空改改看

**Comment by liboy** [comment]
> @liboy这个是这款皮肤自带的效果。
> 
> 代码层面是用CSS实现的
> 
> [HEXO主题，甚至/源/ CSS / _partial / _post / _content.scss](https://github.com/ahonn/hexo-theme-even/blob/8f587a3bc96783753f701680ec1d2b384269b650/source/css/_partial/_post/_content.scss#L13-L16)
> 
> [8f587a3中的](/ahonn/hexo-theme-even/commit/8f587a3bc96783753f701680ec1d2b384269b650) 第13到16 [行](/ahonn/hexo-theme-even/commit/8f587a3bc96783753f701680ec1d2b384269b650)
> 
>  .headerlink {
>    ＆：hover {
>      border-bottom： 0 ;
>    }

@inkydragon 没明白，我要去怎么用这个效果，markdown需要怎么来写？是用HTML来写吗？“##标题 ”这样写出不来这个效果啊？求解答，十分感谢！

**Comment by ahonn** [comment]
@liboy https://github.com/ahonn/hexo-theme-even/issues/222#issuecomment-436234248
