### ISSUE TITLE
如何才能创建categories页面

### ISSUE THREAD

**Issue by xiaotuanyu120** [ahonn/hexo-theme-even#14]
我仿照您tags页面的增加方法
编辑categories/index.md中，增加"layout: categories"

没有任何效果，请问是否可以增加categories

**Comment by ahonn** [comment]
categories 的话 even 目前并没有提供。周末我去加上。

**Comment by liycode** [comment]
@ahonn 我也想要那个功能

**Comment by ahonn** [comment]
@xiaotuanyu120  @liycode  hey，下午刚好有空。
我把 categories 页面加上了，[Document](https://github.com/ahonn/hexo-theme-even/blob/master/doc/doc_zh.md#%E5%88%86%E7%B1%BB%E9%A1%B5) 也更新了。
