### ISSUE TITLE
代码块样式和预览不一致

### ISSUE THREAD

**Issue by Latias94** [ahonn/hexo-theme-even#141]
根据 [issue 96](https://github.com/ahonn/hexo-theme-even/issues/96) 添加了 Go 语言的显示。

在本地预览时，`hexo s`显示的是
![](http://ww4.sinaimg.cn/large/006tKfTcgy1ff4fazbermj30bi04smx8.jpg)

但`hexo d` 上线之后显示的是
![](http://ww1.sinaimg.cn/large/006tKfTcgy1ff4fbu8cryj30be04kwei.jpg)

语法用的是这种形式` ```go tcp-write/main.go`

另外想问问有对不同代码高亮支持的计划吗？

**Comment by ahonn** [comment]
添加了 Go 语言的显示支持。我猜可能是你添加了之后旧的 CSS 文件还在，你需要 `hexo clean`。

另外不同的代码高亮有在计划中，最近有点懒，哈哈哈

**Comment by Latias94** [comment]
`hexo clean` 后解决，感谢。
