### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by vinurs** [ahonn/hexo-theme-even#142]
主题很简洁干净，特别喜欢，建议增加首页文章缩略图功能

**Comment by ahonn** [comment]
你好，能否具体一点？

**Comment by vinurs** [comment]
@ahonn 我原来一直用的是https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak 这个主题，蛮喜欢他的缩略图的功能的，觉得楼主的主题加上以后效果应该是蛮赞的。
一个效果如下：
![72e81a0a-a169-4b3d-9225-52140c24bfa4](https://cloud.githubusercontent.com/assets/2130033/26283905/9079aef4-3e62-11e7-88a1-297feca9806f.png)

类似这种，每篇文章都可以定义一下自己的首页显示的缩略图。
^_^我对前端不懂，要不然就能帮着加上了。

**Comment by vinurs** [comment]
@ahonn 还有文章标题颜色最好加粗，这样看起来明显一点，体验更好点。

**Comment by ahonn** [comment]
我得想想怎么加比较好。明天有空的话我去给加上。
感谢你的建议～

**Comment by vinurs** [comment]
现在这个主题还会更新吗？

**Comment by ahonn** [comment]
更新频率降低，但是还是会更新的。
上次说得缩略图想了想，不好加。因为首页的每篇文章的高度是不同的。
你有什么好方案吗？

**Comment by vinurs** [comment]
@ahonn 没有，可以先参照一下上面的那个主题看一下他是如何实现的。

**Comment by ahonn** [comment]
实现并不是问题。。
问题是每篇文章在首页的高度不同。左侧的缩略图很难做得好看，如果是 100% 宽度的顶部缩略图就没有什么必要了。

**Comment by vinurs** [comment]
@ahonn 首页高度由个人自己控制好了，另外可以设置一个开关来控制首页是否开启缩略图功能。
