### ISSUE TITLE
wiki页面有错

### ISSUE THREAD

**Issue by vinurs** [ahonn/hexo-theme-even#143]
![image](https://cloud.githubusercontent.com/assets/2130033/26283927/053a6b8e-3e63-11e7-9444-8a94e7999e12.png)
这个页面的说明貌似跟**设置移动端导航**没什么关系？直接从安装页面copy过来的？

**Comment by ahonn** [comment]
上个版本留下来的，忘记删除这个链接了。自动跳到安装页面了

**Comment by ahonn** [comment]
已 Fix
