### ISSUE TITLE
theme load error

### ISSUE THREAD

**Issue by Yangxulei** [ahonn/hexo-theme-even#144]
好端端的写了篇文章，然后hexo g  就出现这个错误，换了个主题没问题，不知道怎么回事？
![image](https://cloud.githubusercontent.com/assets/13679239/26410948/3e51d698-40d7-11e7-9efb-11c8d877ed87.png)

**Comment by ahonn** [comment]
能否提供更详细的信息？

**Comment by Yangxulei** [comment]
![image](https://cloud.githubusercontent.com/assets/13679239/26416712/6894316e-40e9-11e7-85dc-c5f166d05fb0.png) 这个信息可以吗？刚才我重新下载并配置了even ，还是出现这个错误。

**Comment by ahonn** [comment]
可能说 Hexo  版本偏低，`hexo -v` 显示是什么版本？最好更新一下
