### ISSUE TITLE
启用网易评论后会出现一个问题

### ISSUE THREAD

**Issue by jsxzljx** [ahonn/hexo-theme-even#145]
如题，
问题环境：
  在您的主题下如果启用网易评论框；
  使用手机浏览器访问或者用电脑Chrome模拟手机来访问

问题描述：
  点击任意一篇博文后无法返回到之前页面！具体来说，安卓手机端点了返回一下，会返回到页首，再点一下才能返回到之前的page；而电脑模拟的时候无法返回，必须手速足够快才行

问题初步分析：
  在使用chrome模拟手机环境访问时，打开审查元素F12，此时点击返回会发现如下错误信息
yunsdk.a51Y02Ndmj6K.14.js:2 Uncaught TypeError: Cannot read property 'yunTie' of null

at yunsdk.a51Y02Ndmj6K.14.js:2

问题初步解决方法：
在主题配置文件里注释掉netease_key，上述症状不再发生

**Comment by ahonn** [comment]
由于网易云跟帖即将关闭，删除了相关功能
