### ISSUE TITLE
Demo 404

### ISSUE THREAD

**Issue by charsdavy** [ahonn/hexo-theme-even#149]
Demo跳转404，看不了预览效果

**Comment by ahonn** [comment]
没有 404 啊

**Comment by charsdavy** [comment]
@ahonn 
![2017-07-05 16 36 33](https://user-images.githubusercontent.com/13601929/27856264-29cc4dcc-61a0-11e7-8cf6-2229895d37f7.png)

**Comment by charsdavy** [comment]
@ahonn 你的链接有问题，多了东西

**Comment by ahonn** [comment]
噢～ 我知道了，是 DNS 解析的问题。
国内默认解析到 coding 了，这个 Demo 在 coding 上没有。所以 404 了。

**Comment by ahonn** [comment]
我把默认解析改到 Github pages 好了。
其实你现在翻个墙就能看到 Demo 了，DNS 解析可能没那么快生效。

**Comment by charsdavy** [comment]
@ahonn 我已经看到了，直接去掉你链接后面那段"hexo-theme-even"就好了

**Comment by ahonn** [comment]
@charsdavy 不不不，这个是另外一个主题..

**Comment by ahonn** [comment]
@charsdavy 可以了，你重新访问 Demo 吧，DNS 生效了。
