### ISSUE TITLE
站内搜索无结果展示

### ISSUE THREAD

**Issue by charsdavy** [ahonn/hexo-theme-even#151]
没法使用本地搜索

**Comment by ahonn** [comment]
请详细描述.. 是否根据文档安装了对应插件？

**Comment by charsdavy** [comment]
hexo-cli: 1.0.3
os: Darwin 16.6.0 darwin x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k

已经安装了`hexo-generator-search`和`hexo-generator-searchdb`,开启了theme serach:true
