### ISSUE TITLE
安装插件一直报错

### ISSUE THREAD

**Issue by wenfeng0218** [ahonn/hexo-theme-even#157]
iFeng-MBP:hexo feng$ npm install hexo-renderer-scss --save

> node-sass@3.13.1 install /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 install /Users/feng/Documents/hexo/node_modules/hexo-renderer-scss/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/feng/Documents/hexo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/feng/Documents/hexo/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/feng/Documents/hexo/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/feng/Documents/hexo/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/feng/Documents/hexo/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/feng/Documents/hexo/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/feng/Documents/hexo/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/feng/Documents/hexo/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/feng/Documents/hexo/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/feng/Documents/hexo/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/feng/Documents/hexo/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/feng/Documents/hexo/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/feng/Documents/hexo/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/feng/Documents/hexo/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/feng/Documents/hexo/node_modules/which/which.js:13:12)\n    at F (/Users/feng/Documents/hexo/node_modules/which/which.js:68:19)\n    at E (/Users/feng/Documents/hexo/node_modules/which/which.js:80:29)\n    at /Users/feng/Documents/hexo/node_modules/which/which.js:89:16\n    at /Users/feng/Documents/hexo/node_modules/isexe/index.js:42:5\n    at /Users/feng/Documents/hexo/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.2.1
gyp verb command install [ '8.2.1' ]
gyp verb install input version string "8.2.1"
gyp verb install installing version: 8.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.2.1
gyp verb build dir attempting to create "build" dir: /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/feng/Documents/hexo/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/feng/Documents/hexo/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/feng/.node-gyp/8.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/feng/.node-gyp/8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/feng/Documents/hexo/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/feng/.node-gyp/8.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/feng/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/feng/.node-gyp/8.2.1/include/node -I/Users/feng/.node-gyp/8.2.1/src -I/Users/feng/.node-gyp/8.2.1/deps/uv/include -I/Users/feng/.node-gyp/8.2.1/deps/v8/include -I../../../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/feng/Documents/hexo/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/feng/Documents/hexo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/feng/Documents/hexo/node_modules/node-sass-selector-importer/node_modules/node-sass
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/feng/.npm/_logs/2017-07-24T14_10_03_768Z-debug.log

**Comment by ahonn** [comment]
很明显，你网络不行。尝试使用代理或者使用 cnpm 安装吧。
