### ISSUE TITLE
Even的5个问题

### ISSUE THREAD

**Issue by plmsmile** [ahonn/hexo-theme-even#160]
### 1. 页面到最后目录消失
一个页面比较长，在前面的时候目录会一直存在。可是当到达页面的末尾的时候，目录就不在了。如[这个接着向下拉](https://plmsmile.github.io/2017/08/04/pgm-01/#观察序列概率)
### 2. 表格显示错误
表格在网页中显示总是会多一列出来，md中没有问题。例如[表格1](https://plmsmile.github.io/2017/08/04/pgm-01/#产生式和判别式)和[表格2](https://plmsmile.github.io/2017/04/04/ml-watermelon-chap1/)
### 3. 多级无序列表
当使用两层的无序列表的时候，仍然显示为一层无序列表
### 4. TODO列表错误
不能显示TODO列表，网页中是以源代码显示的
### 5. 使用方便性问题
在本地起了一个hexo s，打开一个网页(md文件)，当我修改此md文件，再去刷新当前网页，那么整个页面就没有了。不知道是hexo 博客的问题还是主题的问题。

上述问题，辛苦博主解答了~

**Comment by ahonn** [comment]
1. 估计是数学公式的原因导致的，公式是后面加载的，但是目录的获取文章长度时公式还没有加载。所以目前只能滑动到公式未加载前的文章长度的位置。BUG 待修复..
2.表格的问题暂且还不知道是什么问题，能否将这份 md 文件发给我？
3.多级无序列表也是 BUG，待修复..
4.TODO 可以参考 https://github.com/ahonn/hexo-theme-even/issues/135
5.尝试使用 hexo-browsersync 看看能不能解决

以上待修复的问题晚上我回去 Fix 掉，现在不方便弄。感谢反馈。

**Comment by ahonn** [comment]
关于表格的问题，我在我本地跑是没有问题的，我猜测是 markdown 解析的问题，请检查插件的版本。

```
"hexo": "^3.2.0",
"hexo-renderer-marked": "^0.3.0",
```
