### ISSUE TITLE
代码块字体和背景颜色可以修改吗？

### ISSUE THREAD

**Issue by immrss** [ahonn/hexo-theme-even#163]
代码块字体和背景颜色可以修改吗？

**Comment by ahonn** [comment]
在 [_custom.scss](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_custom/_custom.scss) 中添加 [$code-font-family](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss#L192) 与 [$code-background](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss#L231)，并修改为你喜欢的字体与颜色。

所有 [_variables.scss](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss) 中的变量都可以在 _custom.scss 中自定义

**Comment by ahonn** [comment]
如果是代码高亮可以在 _custom.scss 中添加[这个](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss#L195)

具体高亮颜色可参考 higheight.js

**Comment by immrss** [comment]
十分感谢
