### ISSUE TITLE
样式没有加载出来 附链接

### ISSUE THREAD

**Issue by immrss** [ahonn/hexo-theme-even#164]
http://simonyang.cn  按照readme安装的，样式没有加载出来  帮我看看  谢谢！

**Comment by ahonn** [comment]
尝试 `hexo clean`  然后 `hexo s --debug` 看看是不是还是这样

**Comment by immrss** [comment]
还有一个小问题  文章右边的contents 索引可以隐藏掉吗？

**Comment by ahonn** [comment]
https://github.com/ahonn/hexo-theme-even/wiki/%E8%AE%BE%E7%BD%AE%E6%96%87%E7%AB%A0%E7%9B%AE%E5%BD%95

**Comment by immrss** [comment]
# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: false
  fancybox: false

无论是true 还是false 都一只显示呢 http://simonyang.cn
