### ISSUE TITLE
typo in head.jade

### ISSUE THREAD

**Issue by yangg** [ahonn/hexo-theme-even#17]
`meta(name="description", contebt= config.description)`
这里应该是 `content` 吧

**Comment by ahonn** [comment]
yep.. 手抖.. 你好细心..

**Comment by yangg** [comment]
有个问题，能不能将post的title设为文章标题啊，现在好像是整站统一的

**Comment by ahonn** [comment]
Done. 其实你能改的话可以改完给我发 PR 的..

**Comment by yangg** [comment]
tks
后面我发pr吧
