### ISSUE TITLE
报告3个小问题

### ISSUE THREAD

**Issue by olOwOlo** [ahonn/hexo-theme-even#171]
- [x] _variables.scss 中 code-highlight-color 定义为`name`，但_code.scss line 137 使用`title`获取 #170
- [ ] 建议在 .post-content 下添加`word-wrap: break-word;`或`word-break: break-all;`
![snipaste_20170826_214947](https://user-images.githubusercontent.com/26087907/29742109-c41c6aea-8aab-11e7-9d6b-c515ad1e5620.png)
- [ ] 希望小屏幕下弄一个能折叠的目录，在ipad屏幕(1024px)下目录只能显示左边一半

以上desu~

>*话说把这个主题移植到hugo上了，博主不会介意的对吧~*

**Comment by ahonn** [comment]
目录目前应该是不会大改动.. 处理方式是在 1024px 下隐藏掉。
关于移植到 Hugo，非常欢迎～ 之前我也有想过，也尝试写过 hugo 主题，但是同一个主题写两次感觉还是有点烦的 : ) 

最后，感谢你的反馈
