### ISSUE TITLE
主题样式无法显示问题

### ISSUE THREAD

**Issue by Leeericent** [ahonn/hexo-theme-even#172]
我刚刚安装了even的主题, 用hexo s以后在本地的预览只能看到文字而没有样式(就像网页没加css的那种)
原本的默认的主题landscape是能够正常显示的. 我也用hexo clean清除数据库试过了, 还是显示不了样式.
请问有什么解决方法吗?
 `node -v`
v6.11.2
`hexo -v`
hexo: 3.3.8
hexo-cli: 1.0.3
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l

**Comment by ahonn** [comment]
检查是否正确安装 ？ https://github.com/ahonn/hexo-theme-even/wiki

**Comment by Leeericent** [comment]
hexo-renderer-scss已经安装了, 而且安装的时候也没有报错, `hexo g`和`hexo s`的时候也没有报错.

**Comment by ahonn** [comment]
hexo s -debug 之后访问页面显示什么

**Comment by Leeericent** [comment]
还是不能正常显示页面, 但是样式和之前的稍微有点不一样, 具体表现在字体变得大了一些, 并且背景变了(大概在屏幕偏上方有那种类似阴影的颜色)

**Comment by ahonn** [comment]
我是说 debug 模式之后，命令行上打的日志是什么..

**Comment by Leeericent** [comment]
你说的页面我以为指网页...我换了Vps重新安装页面显示正常了, 已经把原来出错的电脑上面的文件给删除了...所以就当这个问题已经解决了吧...
对了, 我还有一个问题, 请问一下网站内部的搜索引擎要怎么加? 就是这个repo里面的readme里面的screen shot那张图片里, 右上角(在Home Archieves右边)有个搜索的标志

**Comment by gejinhudev** [comment]
Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？

**Comment by wishstrive** [comment]
> Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？

请问现在你解决了吗，我也遇到了这样的问题

**Comment by ahonn** [comment]
> > Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？
> 
> 
> 
> 请问现在你解决了吗，我也遇到了这样的问题

重新安装主题也没有解决么？

**Comment by ahonn** [comment]
> > Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？
> 
> 
> 
> 请问现在你解决了吗，我也遇到了这样的问题

麻烦发一下出现问题的仓库以及本地 hexo 的版本哈

**Comment by wishstrive** [comment]
> > > Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？
> > 
> > 
> > 请问现在你解决了吗，我也遇到了这样的问题
> 
> 麻烦发一下出现问题的仓库以及本地 hexo 的版本哈

出现问题的仓库是指theme文件夹吗？

**Comment by wishstrive** [comment]
> > > Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？
> > 
> > 
> > 请问现在你解决了吗，我也遇到了这样的问题
> 
> 麻烦发一下出现问题的仓库以及本地 hexo 的版本哈

![image](https://user-images.githubusercontent.com/75101624/100534972-ba0ab080-324f-11eb-9fe2-681786316e34.png)

**Comment by wishstrive** [comment]
> > > Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？
> > 
> > 
> > 请问现在你解决了吗，我也遇到了这样的问题
> 
> 麻烦发一下出现问题的仓库以及本地 hexo 的版本哈
![image](https://user-images.githubusercontent.com/75101624/100534991-ea524f00-324f-11eb-8a62-4934fe42ec75.png)

**Comment by wishstrive** [comment]
> > > Leeericent, 你好。我也遇到跟你类似的情况，在_config.yml文件中添加theme: even之后，页面就没有了样式，改为themes目录下的next 和 landscape 之后，显示没有问题。就着一个even主题有问题，请问，你当时时怎么解决的？我不太清楚你说的换了vps是什么意思，你能详细说一下吗？
> > 
> > 
> > 请问现在你解决了吗，我也遇到了这样的问题
> 
> 麻烦发一下出现问题的仓库以及本地 hexo 的版本哈

抱歉，我不是用您的主题的。在网上搜索问题于是发现了这个讨论<(_ _)>

**Comment by ahonn** [comment]
@wishstrive 这大概率是缺少主题所需要的插件造成的。看下是不是安装步骤漏了，或者问下主题作者。

**Comment by wishstrive** [comment]
> @wishstrive 这大概率是缺少主题所需要的插件造成的。看下是不是安装步骤漏了，或者问下主题作者。

噢噢，可能是这个原因，主题中所用到的插件都是需要单独下载的吗？
