### ISSUE TITLE
不支持数学公式渲染（mathjax）

### ISSUE THREAD

**Issue by sshuair** [ahonn/hexo-theme-even#178]
目前版本似乎不支持数学公式的渲染呀。

**Comment by ahonn** [comment]
https://github.com/ahonn/hexo-theme-even/issues/41

**Comment by JacobChengZhang** [comment]
今天折腾了好久，谷歌了近两年内的各种方案（hexo-math, hexo-renderer-kramed等等），试了都没效果。最后用[静态SVG](https://reuixiy.github.io/technology/computer/computer-aided-art/2018/05/16/hexo-mathjax-svg.html)的方法成功了，各位可以参考一下。
