### ISSUE TITLE
借楼,感觉站内搜索还是很多人需要的

### ISSUE THREAD

**Issue by bay1** [ahonn/hexo-theme-even#189]
同样不知为何作者撤销了站内搜索功能,自己在借用作者主题的时候,自己添加了这个模块
希望以后有人想添加可以有地方直接clone

[自己增加后的主题源码](https://github.com/bayi27/hexo-theme-even)

# 还是非常感谢原作者的主题开源,很好看!

**Comment by ahonn** [comment]
之前添加过，觉得不好看，感觉怪怪的。就撤掉了。

**Comment by bayi27** [comment]
可能审美不同吧.:alien:

**Comment by LIUYOU2015** [comment]
[自己添加的搜索功能](https://github.com/LIUYOU2015/hexo-theme-even)(主题颜色改成了性冷淡风)
搜索风格借鉴[Nlvi主题](https://github.com/ColMugX/hexo-theme-Nlvi)
感谢 @ColMugX 和 @ahonn 
改动：点击搜索框才下载搜索文件
功能预览参考[本人博客](https://liuyou2015.github.io)

**Comment by colmugx** [comment]
有种风格入侵的感觉..

**Comment by pylixm** [comment]
@bay1  具体搜索实现连接404了，可否补充下。谢谢 ~

**Comment by yxCtgu** [comment]
我很喜欢这个主题的配色，很好看，目前发现不太方便的一些问题说一下：
站内搜索，我感觉还是很重要的，特别是文章一多要找的时候
底部的分页，只有一页一页的翻好像，并没有显示页号
刚接触这个东西，暂时不知道怎么改，有时间还是摸索摸索，倘若作者有时间修改就更好了！
