### ISSUE TITLE
求问Mathjax配置问题

### ISSUE THREAD

**Issue by striderdu** [ahonn/hexo-theme-even#195]
按照一些教程更改渲染引擎之后未果，求问

**Comment by climberpi** [comment]
同问, 似乎是因为用了 hexo-renderer-scss 渲染流程不太一样..

**Comment by climberpi** [comment]
已解决, 可以使用 KaTeX 替代. 

markdown 渲染引擎需要更换成[ hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus), 先卸载其他渲染引擎 (比如 hexo-render-kramed): 
`
npm uninstall hexo-renderer-kramed --save
npm install hexo-renderer-markdown-it-plus --save
`

此外需要手动添加 KaTeX 的 css 文件, 参考[官方指南](https://github.com/khan/katex): 
`
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css" integrity="sha384-TEMocfGvRuD1rIAacqrknm5BQZ7W7uWitoih+jMNFXQIbNl16bO8OZmylH/Vi/Ei" crossorigin="anonymous">
`
添加上述语句到 /themes/even/layout/_script/theme.swig 中, 即
`
<script type="text/javascript" src="{{ url_for('js/src') }}/even.js?v={{ theme.version }}"></script>
<script type="text/javascript" src="{{ url_for('js/src') }}/bootstrap.js?v={{ theme.version }}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css" integrity="sha384-TEMocfGvRuD1rIAacqrknm5BQZ7W7uWitoih+jMNFXQIbNl16bO8OZmylH/Vi/Ei" crossorigin="anonymous">
`

也可以把 katex.min.css 文件放在本地, 比如`\themes\even\source\js\src\katex.min.css`; 那么theme.swig 中的地址部分需要修改为 `href="{{ url_for('js/src') }}/katex.min.css"`.

**Comment by striderdu** [comment]
@climberpi 非常感谢！

**Comment by lizhuohua** [comment]
不错哦，希望能默认支持katex

**Comment by testsiling** [comment]
已添加，依然无果。没有报错，请问自己的_config.yml需要修改吗？

**Comment by corvofeng** [comment]
我在 layout/_script/libs.swig 之中加入这句话之后就可以使用. 

```javascript
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```

**Comment by JieJiSS** [comment]
最新版本已内置 LaTeX 支持
