### ISSUE TITLE
没有样式显示

### ISSUE THREAD

**Issue by gejinhudev** [ahonn/hexo-theme-even#197]
为什么应用even主题，没有样式。删除even文件后，再次重新下载后，能够正常显示。不知道什么原因，想请解释一下。

**Comment by ahonn** [comment]
你想让我解释什么，好歹给点 log？

**Comment by scottboyboy** [comment]
是不是直接在你的blog仓库git clone了？然后成为了子模块，Submodule。我是通过push之后网页发现的，然后执行`git rm --cached themes/even/`删除了子模块，然后ok了。
