### ISSUE TITLE
请问怎么样修改主题的宽度呢？我想让他再宽点

### ISSUE THREAD

**Issue by ddyblackhat** [ahonn/hexo-theme-even#2]

**Comment by ahonn** [comment]
修改 source/less/_partial/media.less 中 @media screen and (min-width: 700px)  body 的 width。
这样需要去重新编译 less，或者直接修改 source/css/style.css 中的。你可能需要格式化一下然后 Find。

有空的话我看看能不能把这个改成可配置的。
最后感谢你的使用~有兴趣的话欢迎 PR ~

**Comment by ddyblackhat** [comment]
没怎么明白，前端的搞不了。部分可以优化下么？
1. 每篇文章可以搞个目录吗？
2. 回顶部
3. about可以评论吗？

**Comment by ahonn** [comment]
好的。明天搞。感谢反馈。




-------- 原始邮件 --------
发件人：ddy <notifications@github.com>
时间：周三 3月30日 23:56
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] 请问怎么样修改主题的宽度呢？我想让他再宽点 (#2)

**Comment by lucmann** [comment]
> 修改 source/less/_partial/media.less 中 @media screen and (min-width: 700px) body 的 width。
> 这样需要去重新编译 less，或者直接修改 source/css/style.css 中的。你可能需要格式化一下然后 Find。
> 
> 有空的话我看看能不能把这个改成可配置的。

页面宽度现在可以配置了吗？而且是否可以每Post可配置？

谢谢！
