### ISSUE TITLE
手机端表格溢出

### ISSUE THREAD

**Issue by wenhui-huang** [ahonn/hexo-theme-even#202]
![773391734439216486](https://user-images.githubusercontent.com/31820155/40266966-7ee24eba-5b87-11e8-8c29-2d274b114f94.jpg)

**Comment by ahonn** [comment]
Fixed

**Comment by wenhui-huang** [comment]
你好，我按照你的提交记录修改了代码，当我执行``hexo g`` ``hexo s``在本地http://localhost:4000 预览博客的时候是没问题的
![1](https://user-images.githubusercontent.com/31820155/40553702-0cee3c80-6076-11e8-9cdd-4487eb625d33.jpg)
可是当我执行``hexo g -d``生成博客后就变成了这样

![2](https://user-images.githubusercontent.com/31820155/40553963-e3bc59ea-6076-11e8-84e4-39060de17acb.jpg)

不仅表格溢出而且连表格的边框都没有了

**Comment by ahonn** [comment]
建议直接更新主题。没有样式是因为你没有修改对应的主题。备份一下_cinfog.yml 然后 git pull 比较好。我加上了 pjax 的支持，体验会更好。
