### ISSUE TITLE
章节标题层次不明显

### ISSUE THREAD

**Issue by jingsam** [ahonn/hexo-theme-even#203]
现在章节标题文件改用宋体后，一级标题、二级标题、三级标题文字大小相近，层次不明显：

![image](https://user-images.githubusercontent.com/1522494/40619870-50f83a34-62c9-11e8-8bbc-36c0165e5a7b.png)

![image](https://user-images.githubusercontent.com/1522494/40619913-7b89bdf4-62c9-11e8-8f61-9df197c1f67e.png)

测试环境： macOS chrome 68

**Comment by loremwalker** [comment]
特别是四、五级标题，就这么“没了”，基本无效果，标题间距也好像有些问题...

**Comment by ahonn** [comment]
你觉得应该怎么设置呗？说出你的解决方案

**Comment by jingsam** [comment]
我觉得标题可设置为30px h1 26px h2 22px h3 18px.h4h5h6我觉得用处不大，真要区分的话，我觉得靠字体大小已经不合适了，可考虑使用衬线体

**Comment by colmugx** [comment]
一般来说正文如果有子标题，都是从二级标题开始。如果觉得大小不合适可以自定义。
