### ISSUE TITLE
处理代码块是哪个模块实现的？

### ISSUE THREAD

**Issue by LIUYOU2015** [ahonn/hexo-theme-even#204]
发现代码块有bug。有的代码可以显示语言，有的不可以。(markdown都已经指定了语言)
比如这样：
```markdown
```JavaScript
function Test(){};
Test.prototype = null;
var a = new Test();
a instanceof Test;
a instanceof Object;
\```

```

就是块的最开始一行，有的会显示‘Python’，有的显示 ‘Code’
[测试](https://liuyou2015.github.io/2018/06/18/测试代码块显示语言/)
想知道这是哪一部分做的工作。

同一种语言（JavaScript）在我的博客里不能显示语言名，但是作者的却可以

**Comment by LIUYOU2015** [comment]
是因为不再code-type-list里面吗？
_variables.scss里有一个list 
通过更改这个list，我加了一部分，但是也仍然有加上的还是无法显示

**Comment by LIUYOU2015** [comment]
看来确实需要手动添加到code-type-list
格式是这样
/node_modules/highlight.js/lib/languages里的语言名：“希望显示的名字”
例如：
```s c s s
$code-type-list: (
  html: "HTML",
  js: "JavaScript",
  javascript: "JavaScript",
  bash: "Bash",
  css: "CSS",
  scss: "Scss" //最后一个不加逗号
) !default;
```

**Comment by LIUYOU2015** [comment]
问题还没有彻底解决，因为我想加一种新的语言：pseudocode。
我需要知道css处理的代码块是哪个部分返回的。

**Comment by ahonn** [comment]
如你所见，定义代码块显示语言的 CSS 在 https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss#L209

如果你要添加语言，在 _custom/custom.scss 中重新定义 $code-type-list 即可，代码高亮用的是 highlight.js。支持的语言包括 [这些](https://github.com/isagalaev/highlight.js/tree/master/src/languages)
