### ISSUE TITLE
博客总数显示不出来

### ISSUE THREAD

**Issue by LIUYOU2015** [ahonn/hexo-theme-even#205]
achieve页面中有这句代码，但是不能显示出来。
```html
<div class="archive-title">
          <span class="archive-post-counter">
            26 Posts In Total
          </span>
</div>
```
比如图片中作者...
<img width="1047" alt="blog num" src="https://user-images.githubusercontent.com/32282247/41815315-79a2fa98-7799-11e8-9065-209dbd45da23.png">

**Comment by ahonn** [comment]
原先是有的，后面为隐藏掉了
