### ISSUE TITLE
如何调整哈代码的 color theme

### ISSUE THREAD

**Issue by ikonglong** [ahonn/hexo-theme-even#214]
个人不喜欢默认的代码 color theme，想换成 solarized-dark
看了 issue 列表，知道要在 _custom/custom.scss 中重新定义相应的变量即可。但是不知道下面每项对应的具体颜色值：
```
// Color of code highlight, solarized.
$code-highlight-color: (
  comment: #93a1a1,
  keyword: #859900,
  number: #2aa198,
  title: #268bd2,
  attribute: #b58900,
  symbol: #cb4b16,
  built_in: #dc322f
) !default;
```

**Comment by JieJiSS** [comment]
参见：

https://github.com/highlightjs/highlight.js/blob/master/src/styles/solarized-dark.css#L15...L72
