### ISSUE TITLE
安全隐患！不应该将所有配置直接写到html中

### ISSUE THREAD

**Issue by yrom** [ahonn/hexo-theme-even#219]
[layout/_partial/head.swig](https://github.com/ahonn/hexo-theme-even/blob/a87cd41bb998d038a208ab6d839bcd7ff3704baa/layout/_partial/head.swig#L44)中 这一行`window.config = {{ JSON.stringify(theme) }};`会暴露一些服务器配置信息（如deploy中的用户名密码），应该只写主题需要的配置，如改为：
```
{% set c = { leancloud: theme.leancloud, toc: theme.toc, fancybox: theme.fancybox, pjax: theme.pjax} %}
<script>
  window.config = {{ JSON.stringify(c) }};
</script>
```

**Comment by ahonn** [comment]
这个 config 里包含的是站点的 _config.yml 以及主题的 _config.yml 信息，这两个文件基本上都是会通过 github 或者其他代码托管平台备份的，其中不会包含什么敏感信息。

建议是好的..但是能否先搞清楚再发..欢迎你来提 PR

**Comment by yrom** [comment]
https://github.com/hexojs/hexo-deployer-ftpsync 这个插件了解一下

**Comment by ahonn** [comment]
soga, 这的确是我的疏忽。欢迎 PR

个人观点，这种可能会被备份到代码托管平台的文件就不应该写有账号密码。不知道 Hexo 官方怎么想的
