### ISSUE TITLE
可以显示行号吗？ 

### ISSUE THREAD

**Issue by chalme** [ahonn/hexo-theme-even#22]
我用了网上的方法 还是不行。

**Comment by ahonn** [comment]
这个是因为我直接把行号隐藏了，本身就是不显示的。好像是会有这个需求，我待会把它改了。

**Comment by ahonn** [comment]
现在，你可以修改站点配置文件中的 line_number 来选择开启或关闭代码块行号。：）

**Comment by chalme** [comment]
好像 代码中不能有 空行 是不？

**Comment by ahonn** [comment]
可以啊，我博客上不是有代码块里面是有空行的吗



On August 4, 2016 at 17:37:09, chalme (notifications@github.com<mailto:notifications@github.com>) wrote:

好像 代码中不能有 空行 是不？

**Comment by chalme** [comment]
行号    和代码 没有对齐


在 2016年08月04日 17:40, Yuexun 写道:
> 可以啊，我博客上不是有代码块里面是有空行的吗
>
>
>
> On August 4, 2016 at 17:37:09, chalme

**Comment by chalme** [comment]
我显示的效果是这样子。

**Comment by chalme** [comment]
你之前没有行号显示正常，现在有点问题了。  [我的blog 事例在最后](http://talme.cn/2016/08/04/git%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95%E5%92%8C%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9/)
`
```cpp
#include <iostream>
using namespace std;

int main() {
    cout << "hello, world" <<endl;
}
```

`

**Comment by ahonn** [comment]
@chalme  这的确是 bug。之前忽略行号的，早上加的时候写得不是很好。现在修

**Comment by chalme** [comment]
麻烦你了，我不太懂前段。  问一下，你的不支持    codeblock


在 2016年08月04日 19:20, Yuexun 写道:
>
> @chalme <https://github.com/chalme> 这的确是 
> bug。之前忽略行号的，早上加的时候写得不是很好。现在修
>

**Comment by ahonn** [comment]
codeblock ? 代码块支持的啊。``` 包起来不行？

**Comment by chalme** [comment]
哦， 可能你把那个修复了就好了。   codeblock 里面参数可以控制 是否显示行号


在 2016年08月04日 19:25, Yuexun 写道:

**Comment by chalme** [comment]
我确定 可以吗？  我的还是那样子。


在 2016年08月04日 19:35, Yuexun 写道:

**Comment by ahonn** [comment]
换成 ``` 包住的写发也是？F12 看到的 padding 的确是 0，但是显示出来的却是有 padding 的。上面那些代码块看起来没事的样子。我也是很懵逼。

**Comment by chalme** [comment]
研究一下， 你的前段路。


在 2016年08月04日 19:43, Yuexun 写道:

**Comment by chalme** [comment]
我发现错误的地方了，  当写代码的时候，  回收换行的时候， 
需要在那一行加个空格，然后markdown 
就可以识别了。不加的话就为空，高度就不对了。

你看一下，怎么修改一下。


在 2016年08月04日 19:43, Yuexun 写道:

**Comment by ahonn** [comment]
oh, I see. 我已经 fix 它了。

**Comment by chalme** [comment]
我还以为 .line  是自动生成的， 不能用css 控制，原来就是加那一句。
在 2016年08月04日 20:59, Yuexun 写道:

**Comment by chalme** [comment]
onemorethings,  官方有这样子的用法， 没有设置吧 ？

{% codeblock [title] [lang:language] [url] [link text] %}
code snippet
{% endcodeblock %}


在 2016年08月04日 20:59, Yuexun 写道:

**Comment by ahonn** [comment]
这个我不打算实现。

balabala...
\`\`\` [language]
code snippet
\`\`\`

倾向这种写法，那种写法太繁琐了。
给代码块加那个 title 太丑了，不如在上面写。

**Comment by chalme** [comment]
嗯嗯。我是发现有两个比较用用的地方，  可以添加链接，，， 
也可以控制代码是否显示行号和高亮


在 2016年08月04日 23:30, Yuexun 写道:
