### ISSUE TITLE
不支持脚注（Footnote）

### ISSUE THREAD

**Issue by sdjk** [ahonn/hexo-theme-even#221]
- 脚注内容无法显示
- 在正文中显示也是`[^*]`形式

**Comment by kchen0x** [comment]
欢迎使用我的插件 [hexo-reference](https://github.com/kchen0x/hexo-reference)

**Comment by sherliynchen** [comment]
卸载原有的默认渲染插件`marked` ，然后装 [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it) 。
