### ISSUE TITLE
为什么在 h2~h6 标题前面有个<a>标签？

### ISSUE THREAD

**Issue by kchen0x** [ahonn/hexo-theme-even#222]

**Comment by kchen0x** [comment]
关键是<a>标签还有 ::before{content} 属性，导致每个标题前面都有一个空格。

这样看上去就像标题有一个小缩进。

**Comment by ahonn** [comment]
这个之前没有处理好，原来在标题前面是有一个 “#” 之类的符号的, 见 https://github.com/ahonn/hexo-theme-even/commit/32cf242d84115c7315e86bda44cf99941de9b4b5#diff-e3625e5d5b62f2a9239e62b08debb4b7L170

但后面把默认设置为空的时候样式忘记处理了，现在已经处理了。你可以更新完再试一下。
感谢你的细心反馈 👍

**Comment by ahonn** [comment]
BTW, 标题前面的 a 标签其实是个锚点来的，你可以通过这样的 URL: https://www.ahonn.me/2018/09/15/javascript-functional-programming-notes/#functor 来跳转到对应的标题上

**Comment by kchen0x** [comment]
其实我就是在给标题前面加 “¶”“§”的时候发现的。配置里面有地方可以快速加么？我自己去改了

```
@for $i from 1 through 6 {
    h#{$i} {
      font-weight: 400;
      font-family: $global-serif-font-family;
    }
    h#{$i}::before {
      content: "§";
      font-family: $global-font-family;
    }
  }
```

好像有点不雅。

**Comment by ahonn** [comment]
你可以在 https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_custom/_custom.scss 中添加 `$content-headings-anchor: "¶";`, 这样就可以了。

所有 https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_variables.scss  中的变量都可以在上面那个自定义文件中复写。
