### ISSUE TITLE
hexo Script load failed: themes\icarus\scripts\index.js

### ISSUE THREAD

**Issue by liusih** [ahonn/hexo-theme-even#223]
![image](https://user-images.githubusercontent.com/31608942/48946871-11435f80-ef6a-11e8-8edc-773820e04136.png)

\themes\icarus\includes\specs\config.spec.js:14
    ...require('./meta.spec'),
SyntaxError: Unexpected token ...

code in '...' is wrong.......

**Comment by ahonn** [comment]
> \themes\icarus\...

**Comment by wangcc7** [comment]
what？
