### ISSUE TITLE
配置后 首页显示extends partial/layout include mixins/container include mixins/paginator block title title= config.title block container +home() block pagination +paginator('home') 

### ISSUE THREAD

**Issue by imzyf** [ahonn/hexo-theme-even#23]
extends partial/layout include mixins/container include mixins/paginator block title title= config.title block container +home() block pagination +paginator('home') 

是我哪里有问题呢？

**Comment by ahonn** [comment]
那些插件都安装了吗？

**Comment by imzyf** [comment]
安装了

**Comment by ahonn** [comment]
那就奇怪了。如果可以的话截个报错信息的图。Title 上那样说什么都看不出来..

**Comment by imzyf** [comment]
.. 下午又弄了下，没改什么，然后上午的问题不复现了，但是 blog 只有文字，没有css
![image](https://cloud.githubusercontent.com/assets/9289792/17391441/b9fcebdc-5a48-11e6-92de-ee706982507f.png)

**Comment by ahonn** [comment]
感觉删掉重新弄会好一点..

**Comment by imzyf** [comment]
非常迷；看起来现在正常能用了。

**Comment by imzyf** [comment]
还有个问题 
为什么 在 node_modules 中

abab                  for-in                    node-fingerprint
abbrev                form-data                 node-uuid
accepts               for-own                   nopt
acorn                 fresh                     normalize-path
acorn-globals         generate-function         nth-check
amdefine              generate-object-property  number-is-nan
ansi-regex            getpass                   nunjucks
ansi-styles           get-stdin                 nwmatcher
anymatch              glob                      oauth-sign
archy                 glob-base                 object-assign
argparse              glob-parent               object.omit
array-unique          graceful-fs               once
arr-diff              graceful-readlink         on-finished
arr-flatten           har-validator             on-headers
arrify                has-ansi                  opn
asap                  hawk                      optimist
asn1                  hexo                      optionator
assert-plus           hexo-front-matter         os-homedir
async                 hexo-fs                   os-locale
async-each            hexo-generator-archive    parse5
aws4                  hexo-generator-category   parse-glob
aws-sign2             hexo-generator-index      parseurl
balanced-match        hexo-generator-tag        path-is-absolute
basic-auth            hexo-i18n                 pinkie
binary-extensions     hexo-log                  pinkie-promise
bl                    hexo-pagination           prelude-ls
bluebird              hexo-renderer-ejs         preserve
boolbase              hexo-renderer-jade        pretty-hrtime
boom                  hexo-renderer-marked      process-nextick-args
brace-expansion       hexo-renderer-stylus      promise
braces                hexo-server               pseudomap
browser-fingerprint   hexo-util                 qs
buffer-shims          highlight.js              randomatic
bunyan                hoek                      range-parser
bytes                 html-entities             readable-stream
camelcase             htmlparser2               readdirp
camel-case            http-errors               regex-cache
caseless              http-signature            repeat-element
chalk                 inflight                  repeat-string
character-parser      inherits                  request
cheerio               invert-kv                 rimraf
chokidar              isarray                   safe-json-stringify
clean-css             is-binary-path            sax
cliui                 is-buffer                 send
code-point-at         is-dotfile                serve-static
combined-stream       is-equal-shallow          set-immediate-shim
commander             isexe                     setprototypeof
compressible          is-extendable             sigmund
compression           is-extglob                sntp
concat-map            is-fullwidth-code-point   source-map
connect               is-glob                   sprintf-js
constantinople        is-my-json-valid          sshpk
core-js               is-number                 statuses
core-util-is          isobject                  string_decoder
cross-spawn           is-plain-object           stringstream
cryptiles             is-posix-bracket          string-width
css                   is-primitive              strip-ansi
cssom                 is-promise                strip-indent
css-parse             is-property               striptags
css-select            isstream                  stylus
css-stringify         is-typedarray             supports-color
cssstyle              jade                      swig
css-what              jodid25519                swig-extras
cuid                  jsbn                      symbol-tree
dashdash              jsdom                     text-table
debug                 jsonparse                 through
decamelize            jsonpointer               tildify
deep-is               json-schema               titlecase
delayed-stream        JSONStream                tough-cookie
depd                  json-stringify-safe       tr46
destroy               jsprim                    transformers
domelementtype        jstransformer             tunnel-agent
domhandler            js-yaml                   tweetnacl
dom-serializer        kind-of                   type-check
domutils              lcid                      uglify-js
dtrace-provider       levn                      uglify-to-browserify
ecc-jsbn              lodash                    unpipe
ee-first              lower-case                upper-case
ejs                   lru-cache                 util-deprecate
encodeurl             markdown                  utils-merge
entities              marked                    vary
escape-html           micromatch                verror
escape-string-regexp  mime                      void-elements
escodegen             mime-db                   warehouse
esprima               mime-types                webidl-conversions
estraverse            minimatch                 whatwg-url-compat
esutils               minimist                  which
etag                  mkdirp                    window-size
expand-brackets       moment                    with
expand-range          moment-timezone           wordwrap
extend                morgan                    wrap-ansi
extglob               ms                        wrappy
extsprintf            mv                        xml-name-validator
fast-levenshtein      nan                       xtend
filename-regex        ncp                       y18n
fill-range            negotiator                yallist
finalhandler          nib                       yargs
forever-agent         no-case


有这么多文件夹？原来就有 hexo 开头的，新增的是什么呢？
ubuntu

**Comment by ahonn** [comment]
那些插件上面的依赖的库



On August 4, 2016 at 15:24:18, Yifans_Z (notifications@github.com<mailto:notifications@github.com>) wrote:

还有个问题
为什么 在 node_modules 中

abab for-in node-fingerprint
abbrev form-data node-uuid
accepts for-own nopt
acorn fresh normalize-path
acorn-globals generate-function nth-check
amdefine generate-object-property number-is-nan
ansi-regex getpass nunjucks
ansi-styles get-stdin nwmatcher
anymatch glob oauth-sign
archy glob-base object-assign
argparse glob-parent object.omit
array-unique graceful-fs once
arr-diff graceful-readlink on-finished
arr-flatten har-validator on-headers
arrify has-ansi opn
asap hawk optimist
asn1 hexo optionator
assert-plus hexo-front-matter os-homedir
async hexo-fs os-locale
async-each hexo-generator-archive parse5
aws4 hexo-generator-category parse-glob
aws-sign2 hexo-generator-index parseurl
balanced-match hexo-generator-tag path-is-absolute
basic-auth hexo-i18n pinkie
binary-extensions hexo-log pinkie-promise
bl hexo-pagination prelude-ls
bluebird hexo-renderer-ejs preserve
boolbase hexo-renderer-jade pretty-hrtime
boom hexo-renderer-marked process-nextick-args
brace-expansion hexo-renderer-stylus promise
braces hexo-server pseudomap
browser-fingerprint hexo-util qs
buffer-shims highlight.js randomatic
bunyan hoek range-parser
bytes html-entities readable-stream
camelcase htmlparser2 readdirp
camel-case http-errors regex-cache
caseless http-signature repeat-element
chalk inflight repeat-string
character-parser inherits request
cheerio invert-kv rimraf
chokidar isarray safe-json-stringify
clean-css is-binary-path sax
cliui is-buffer send
code-point-at is-dotfile serve-static
combined-stream is-equal-shallow set-immediate-shim
commander isexe setprototypeof
compressible is-extendable sigmund
compression is-extglob sntp
concat-map is-fullwidth-code-point source-map
connect is-glob sprintf-js
constantinople is-my-json-valid sshpk
core-js is-number statuses
core-util-is isobject string_decoder
cross-spawn is-plain-object stringstream
cryptiles is-posix-bracket string-width
css is-primitive strip-ansi
cssom is-promise strip-indent
css-parse is-property striptags
css-select isstream stylus
css-stringify is-typedarray supports-color
cssstyle jade swig
css-what jodid25519 swig-extras
cuid jsbn symbol-tree
dashdash jsdom text-table
debug jsonparse through
decamelize jsonpointer tildify
deep-is json-schema titlecase
delayed-stream JSONStream tough-cookie
depd json-stringify-safe tr46
destroy jsprim transformers
domelementtype jstransformer tunnel-agent
domhandler js-yaml tweetnacl
dom-serializer kind-of type-check
domutils lcid uglify-js
dtrace-provider levn uglify-to-browserify
ecc-jsbn lodash unpipe
ee-first lower-case upper-case
ejs lru-cache util-deprecate
encodeurl markdown utils-merge
entities marked vary
escape-html micromatch verror
escape-string-regexp mime void-elements
escodegen mime-db warehouse
esprima mime-types webidl-conversions
estraverse minimatch whatwg-url-compat
esutils minimist which
etag mkdirp window-size
expand-brackets moment with
expand-range moment-timezone wordwrap
extend morgan wrap-ansi
extglob ms wrappy
extsprintf mv xml-name-validator
fast-levenshtein nan xtend
filename-regex ncp y18n
fill-range negotiator yallist
finalhandler nib yargs
forever-agent no-case

有这么多文件夹？原来就有 hexo 开头的，新增的是什么呢？
ubuntu
