### ISSUE TITLE
修改swig模板以移除生成的HTML中的不必要的大量空行

### ISSUE THREAD

**Issue by JieJiSS** [ahonn/hexo-theme-even#231]
swig模板里的所有控制流和最终条件渲染时不会渲染的HTML都会变成空行，导致生成的HTML里`<head>`和`<footer>`等部分出现大量连续的空行，例如：
```
"        \n     \n      \n"
```

根据swig的[官方文档](https://node-swig.github.io/swig-templates/docs/#whitespace)，在swig模板里将
```swig
{% ... %}
```
替换为
```swig
{%- ... -%}
```
可以使得swig引擎在渲染时不保留这些语句对应的空行。有助于减小HTML的体积（在我的用例中，减小了`12%`）

**Comment by JieJiSS** [comment]
如果作者有意向接受这个修改，我可以提交PR。

**Comment by ahonn** [comment]
欢迎 PR

**Comment by JieJiSS** [comment]
@ahonn see PR #232
