### ISSUE TITLE
开启pjax后，点击页面底部按钮切换页面时fancybox不会初始化

### ISSUE THREAD

**Issue by JieJiSS** [ahonn/hexo-theme-even#234]
目前判断这是因为 `pjax` 的工作方式导致所有的加载时触发的 DOM 事件都不会被触发，例如：

+ `DOMContentLoaded`
+ `load`

所以切换到新页面后（有时需要换页两三次） fancybox 不会初始化导致点击图片无反应，且 MathJax 也不会渲染 inline math。因为 `pjax` 换页时不会修改 `<head>` 标签，所以 inline math rendering 我通过在 `<head>` 标签里写 `<script>`，靠 `setInterval` 暴力解决了。但似乎在换页后直接用 `js/src/even.js` 里的初始化代码没法让 fancybox 正确工作。

有没有什么 workaround 呢？

---

又及，由于 `pjax` 换页时不会修改 `<head>` 标签，所以可能导致从 `archive` / `tags` 页面进入文章时，`<head>` 里引入的 CSS / JS 仍然是 `archive` / `tags` 页的，并没有加载 `post` 页所需要的资源。

**Comment by JieJiSS** [comment]
补充信息：查到了一个类似的 [issue](https://github.com/chrisguitarguy/pjaxy/issues/1#issuecomment-7398731)，其中提到可以监听 `pjax:success` 事件。

**Comment by JieJiSS** [comment]
已经定位到了 Bug，我现在已经有一个 Open 状态的 PR 了（ #231 ），我会继续在那里提交 patch

**Comment by ahonn** [comment]
麻烦新开一个 PR 哈，之前那个我合并了

**Comment by JieJiSS** [comment]
@ahonn see PR #235
