### ISSUE TITLE
请问怎么更改字体？

### ISSUE THREAD

**Issue by herseus** [ahonn/hexo-theme-even#239]

**Comment by ahonn** [comment]
见 [修改主题颜色](https://github.com/ahonn/hexo-theme-even/wiki/%E4%BF%AE%E6%94%B9%E4%B8%BB%E9%A2%98%E9%A2%9C%E8%89%B2)

与修改主题颜色同理，_variables.scss 中的样式变量都可以在 _custom.scss 中进行覆盖，从而自定义主题样式
