### ISSUE TITLE
表格为什么显示不出来

### ISSUE THREAD

**Issue by motcwang** [ahonn/hexo-theme-even#24]
如题

**Comment by motcwang** [comment]
额 ，是我理解错了，表格的样式不好看，没有线

**Comment by ahonn** [comment]
我加了点样式，不知道合不合胃口。之前自己都没在博客里面用过表格，所以没注意到..

感谢反馈~

**Comment by motcwang** [comment]
@ahonn 嗯，现在看着好多了，之前因为是没有分割线，所以表格看着不明显。谢谢。
