### ISSUE TITLE
无法在 _custom.scss 中使用 _variable.scss 里定义的变量

### ISSUE THREAD

**Issue by JieJiSS** [ahonn/hexo-theme-even#242]
似乎根据 [#222(comment)](https://github.com/ahonn/hexo-theme-even/issues/222#issuecomment-436234248)，_custom.scss 可以覆写 _variable.scss

但是如果想在 _custom.scss 里使用 _variable.scss 里定义的变量，该如何操作呢

**Comment by JieJiSS** [comment]
个人认为_custom.scss其实不应该全局覆写_variable.scss，如果想修改的话直接去_variable.scss里改

**Comment by ahonn** [comment]
> 个人认为_custom.scss其实不应该全局覆写_variable.scss，如果想修改的话直接去_variable.scss里改

最好还是不需要动主题动代码比较好。我把 _custom.scss 放到了 _variable.scss 之后，这样就即可以覆盖 _variable.scss 中到样式变量，也可以使用现有到样式变量了。

**Comment by JieJiSS** [comment]
👌thx a lot!
