### ISSUE TITLE
ubuntu firefox浏览器,标题字体发虚.

### ISSUE THREAD

**Issue by xunni1000** [ahonn/hexo-theme-even#254]
一点都不圆润.
麻烦作者帮忙盘它!!!!!!!

顶部导航字体在ubuntu发虚

另外内页右边导航

https://r.photo.store.qq.com/psb?/V13iVwZo2obvUj/mcso4HdNjYcQEDR6Rk.pfVbvSA6O5Zg9*pPsj3vMJJ4!/r/dL4AAAAAAAAAnull/_yake_qzoneimgout.png

**Comment by ahonn** [comment]
手头上没有 ubuntu 来测试，不过你可以在 https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_custom/_custom.scss 中对字体进行自定义来解决这个问题。

衬线字体可以在 _custom.scss 中加入：

```scss
$global-serif-font-family: {你想要用的字体}
```

主题会优先使用配置的字体。
