### ISSUE TITLE
page height is too large with a long blank space

### ISSUE THREAD

**Issue by Liooo** [ahonn/hexo-theme-even#259]
like below, height seems too high in `/post/*` page, even in demo site.
https://themes.gohugo.io//theme/hugo-theme-even/post/markdown-syntax/

![heightwrong](https://user-images.githubusercontent.com/1630378/74224167-a2cbf800-4cfb-11ea-8ba9-c22948294b7b.gif)

Just confirmed this happens only when there's headings (`# title`, `## title2` etc) in the post markdown. The issue isn't reproduced after removing all heading lines from the file.

**Comment by ahonn** [comment]
Actually this is a repo for hexo-them-even, not hugo-theme-even. hexo-theme-event's demo does not have this issue.

[hugo-theme-even](https://github.com/olOwOlo/hugo-theme-even) is a port of the hexo-theme-even.
I suggest you open a new issue at https://github.com/olOwOlo/hugo-theme-even/issues to resolve

**Comment by Liooo** [comment]
@ahonn damn didn't notice that sorry.
I was actually using hugo's even theme as you pointed out, and seems like it's fixed by https://github.com/olOwOlo/hugo-theme-even/issues/223
