### ISSUE TITLE
减少更新主题时不必要的麻烦

### ISSUE THREAD

**Issue by ahonn** [ahonn/hexo-theme-even#26]
现在主题中不再有 `_config.yml` 文件，主题配置文件的模板为 `_config.yml.sample`。

第一次使用该主题时需要手动创建 `_config.yml` 并将 `_config.yml.sample` 中的内容复制其中再根据个人需要修改。

`git pull` 更新主题时无需再进行重新的配置，但是此次更新依旧需要事先备份原有的 `_config.yml`（会重命名为 `_config.yml.sample` 并修改内容）。之后的 update 都不会再修改 `_config.yml` 文件，可直接更新使用。

**Comment by ahonn** [comment]
@yangg

**Comment by yangg** [comment]
好的，知道了，多谢！
