### ISSUE TITLE
主题文件和站点文件覆盖问题

### ISSUE THREAD

**Issue by ttttmr** [ahonn/hexo-theme-even#261]
当前目录结构
```
source
  - favicon.ico
  - robots.txt
theme
  - even
    - favicon.ico
    - robots.txt
```
期望是这样source下的文件会被使用，实际情况是主题的文件被使用，也就是generator之后public文件夹中仍然是主题文件

**Comment by ahonn** [comment]
这个行为是由 Hexo 控制的，主题本身没有做设置

**Comment by ttttmr** [comment]
了解了，那这样必须覆盖主题文件才能自定义了，其实这样不便于主题更新，favicon.ico看到有设置可以改，robots.txt就没办法了
