### ISSUE TITLE
主题设置中无法更改主题的颜色

### ISSUE THREAD

**Issue by afrunk** [ahonn/hexo-theme-even#264]
我将主题中的颜色配置处进行修改 发现始终无法奏效

```
# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color:  cobalt blue
```

这是为什么呢？

**Comment by afrunk** [comment]
最后我直接在themes\even\source\css\_variables.scss 下修改了默认主题的颜色，实现了颜色的变化

**Comment by ahonn** [comment]
@afrunk 尝试一下给 cobalt blue 加个引号

**Comment by afrunk** [comment]
@ahonn 是的，我加了引号之后实现了主题的变化，谢谢你。

**Comment by chenamy2017** [comment]
但是我的增加了引号（单引号，双引号都不行），还是未起效
# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: 'mint green'

**Comment by chenamy2017** [comment]
# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: "mint green"

**Comment by ahonn** [comment]
@chenamy2017 node_modules 删掉重新安装试一下

**Comment by chenamy2017** [comment]
> @chenamy2017 node_modules 删掉重新安装试一下

果然奏效，感谢秒回复~
