### ISSUE TITLE
languages 文件夹下的语言文件名是否应该大写？

### ISSUE THREAD

**Issue by loveshizuka** [ahonn/hexo-theme-even#270]
站点设置 language: zh-CN，但是主题语言中文未生效。

将 languages 文件夹下的 zh-cn.yml 改成 zh-CN.yml 则生效。所以 zh-cn.yml 和 zh-tw.yml 是否应该改成 zh-CN.yml 和 zh-TW.yml？

**Comment by ahonn** [comment]
是的，理论上用  zh-CN 才更规范。原先可能是因为在 macOS 下不区分大小写所以没发现。
你能够帮我改一下发个 PR 么？

**Comment by loveshizuka** [comment]
已 PR。
