### ISSUE TITLE
是不是没有支持多级列表

### ISSUE THREAD

**Issue by clxsh** [ahonn/hexo-theme-even#273]
我在typora中编辑的多级列表，没有办法正常渲染呢

**Comment by onns** [comment]
我之前也遇到过这个问题，不过你有截图吗？我看一下
[https://onns.xyz/blog/2020/06/15/hexo-plugin-test/#markdown-%E6%B8%B2%E6%9F%93](https://onns.xyz/blog/2020/06/15/hexo-plugin-test/#markdown-%E6%B8%B2%E6%9F%93)我这里倒是可以，不知道是不是你想要的效果。

**Comment by clxsh** [comment]
> 我之前也遇到过这个问题，不过你有截图吗？我看一下
> https://onns.xyz/blog/2020/06/15/hexo-plugin-test/#markdown-%E6%B8%B2%E6%9F%93我这里倒是可以，不知道是不是你想要的效果。

<img width="1916" alt="cut" src="https://user-images.githubusercontent.com/19650418/100617920-17892500-3356-11eb-8c1c-21b8cba3d36a.png">
就情况是这种，出现了奇怪的换行，没有识别成多级列表

**Comment by onns** [comment]
themes/even/source/css/_partial/_post/_content.scss
这个文件

ul {
&nbsp; &nbsp; padding-left: 0;
&nbsp; &nbsp; list-style: inside;
把这两行注释掉应该就可以解决，但是我不知道会不会有其它的bug出现，所以我就没push给作者，你试试。
大概在41行左右的位置

**Comment by clxsh** [comment]
> themes/even/source/css/_partial/_post/_content.scss 这个文件 ul { &nbsp; &nbsp; padding-left: 0; &nbsp; &nbsp; list-style: inside; 把这两行注释掉应该就可以解决，但是我不知道会不会有其它的bug出现，所以我就没push给作者，你试试。 大概在41行左右的位置

解决啦，谢谢
