### ISSUE TITLE
关闭默认的百度云推送

### ISSUE THREAD

**Issue by jingsam** [ahonn/hexo-theme-even#286]
没有用百度云推送功能，但生成的页面自动加载了百度云推送的脚本，有没有方式可以关闭，谢谢

https://github.com/ahonn/hexo-theme-even/blob/5b19be5bf991c34997756d5de37cf2c588307f8d/layout/_script/push.swig#L1-L14

**Comment by ahonn** [comment]
@jingsam 已支持关闭，见 https://github.com/ahonn/hexo-theme-even/blob/master/_config.yml.example#L87
