### ISSUE TITLE
Add nunjucks support?

### ISSUE THREAD

**Issue by masterrite** [ahonn/hexo-theme-even#293]
hexo-renderer-swig is deprecated. Is there any chance to add support for nunjucks renderer? Thanks

**Comment by zeed-w-beez** [comment]
I changed swig to ejs: <https://zeed-w-beez.github.io/2023/10/10/hexo/swig-to-ejs/>

**Comment by masterrite** [comment]
@zeed-w-beez 
Thanks very much! Do you know how I can change the pulsing heart in the footer into my custom favicon in sources? I tried to point to it with "site/source/favicon.ico" but that didn't work

**Comment by ahonn** [comment]
It looks great, can you request a PR to merge it in?

**Comment by ahonn** [comment]
@zeed-w-beez It looks great, can you request a PR to merge it in?

**Comment by zeed-w-beez** [comment]
> @zeed-w-beez It looks great, can you request a PR to merge it in?

抱歉没注意到你发的消息，我后面几天准备一个“干净”的 PR 。

**Comment by zeed-w-beez** [comment]
非常感谢你设计的这个主题！

**Comment by zeed-w-beez** [comment]
> @zeed-w-beez Thanks very much! Do you know how I can change the pulsing heart in the footer into my custom favicon in sources? I tried to point to it with "site/source/favicon.ico" but that didn't work

![image](https://github.com/ahonn/hexo-theme-even/assets/20834022/cc75e4e6-fd8f-40b4-a909-b903690cb3ac)

**Comment by masterrite** [comment]
> > @zeed-w-beez Thanks very much! Do you know how I can change the pulsing heart in the footer into my custom favicon in sources? I tried to point to it with "site/source/favicon.ico" but that didn't work
> 
> ![image](https://private-user-images.githubusercontent.com/20834022/302020396-cc75e4e6-fd8f-40b4-a909-b903690cb3ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjMzNzMsIm5iZiI6MTcwNzAyMzA3MywicGF0aCI6Ii8yMDgzNDAyMi8zMDIwMjAzOTYtY2M3NWU0ZTYtZmQ4Zi00MGI0LWE5MDktYjkwMzY5MGNiM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA1MDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4N2QzN2M2ZTk4Y2ZjNTYyNDE5MGE5ZGUwODk0NWNjYjk0N2E5OTQzYTg4NzM3N2Y2MDY0YmNkMDdlYWNlMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dp45N74d1TK9-ZbvqXYG0QHForpDpBdCt_vKDJ5sw7U)

Thanks again!

**Comment by ahonn** [comment]
@zeed-w-beez  Thank you for your contribution.

The theme has now been updated to remove the dependency on hexo-renderer-swig and instead uses ejs for template rendering. Additionally, it has been changed to use hexo-renderer-dartsass to avoid the need for node-gyp compilation.
