### ISSUE TITLE
目录无法跟随文章移动

### ISSUE THREAD

**Issue by Buttiyeeppp** [ahonn/hexo-theme-even#296]
您好，目前我使用的是最新版本的 hexo 和 even。
出现了文章目录无法跟随文章移动的问题。（文章下移后就看不见目录了）
看了下 [Even Live Preview](https://ahonn.github.io/hexo-theme-even/2024/02/04/hello-world/) 也是如此。

**Comment by PeakJ** [comment]
是因为引用的jQuery等lib路径失效导致的，已经pr修复了, 克隆最新代码吧

**Comment by PeakJ** [comment]
> 您好，目前我使用的是最新版本的 hexo 和 even。 出现了文章目录无法跟随文章移动的问题。（文章下移后就看不见目录了） 看了下 [Even Live Preview](https://ahonn.github.io/hexo-theme-even/2024/02/04/hello-world/) 也是如此。

是因为引用的jQuery等lib路径失效导致的，已经pr修复了, 克隆最新代码吧
