### ISSUE TITLE
没有评论功能

### ISSUE THREAD

**Issue by envyandgreed** [ahonn/hexo-theme-even#30]
设置了多说的id，并且文章和单页的评论设置为true，但是文章下面没有评论框出现。。。

**Comment by envyandgreed** [comment]
还有就是邮件链接设置后，单击变为404。。。

**Comment by ahonn** [comment]
disqus 的选项是否有注释掉？ 没有的话会默认使用 disqus。

邮件链接是指？

**Comment by ahonn** [comment]
噢~ 原先那个 email 地址在配置文件里面是要带 `mailto:` 的。

现在我把它改成了自动添加了。

**Comment by envyandgreed** [comment]
好的！非常感谢！很优雅的主题，请问可以在站点配置文件config下选择语言吗，因为页面的标签好像不是英语，我想换成英语的或者是中文的，在language后面加什么呢？

**Comment by envyandgreed** [comment]
灰常感谢~~~~很漂亮的主题很喜欢~~~
