### ISSUE TITLE
在文章中使用 `{{ }}` 无法显示的解决办法

### ISSUE THREAD

**Issue by ahonn** [ahonn/hexo-theme-even#32]
由于 `{{ }}` 在 Hexo 解析的时候会当成变量，所以当类似  `{{ message }}` 这种出现在文章中时，将无法显示。

具体解决方案可以查看 [hexo issue 1079](https://github.com/hexojs/hexo/issues/1079)

将 `{{ }}` 以转码后的形式写在文章中，或者使用 [raw block](https://hexo.io/docs/troubleshooting.html#Escape-Contents)

**Comment by ahonn** [comment]
@Baoyx007  解决办法在这里。

**Comment by Baoyx007** [comment]
Ok, 谢谢~

**Comment by envyandgreed** [comment]
你好，首页的标签有时候不是英文是怎么回事呀

**Comment by ahonn** [comment]
修改 `_config.yml` 中的语言即可



On August 13, 2016 at 00:37:47, envyandgreed (notifications@github.com<mailto:notifications@github.com>) wrote:

你好，首页的标签有时候不是英文是怎么回事呀

**Comment by envyandgreed** [comment]
好的，感谢~

**Comment by crifan** [comment]
谢谢。Gitbook中的markdown也是遇到同样问题，最后用：
````
`http://{% raw %}{{% endraw %}{server_address}}/ucows/login/login`
````
实现了要显示的效果：
![gitbook_md_code_brace](https://user-images.githubusercontent.com/2750682/34431212-2e6883c6-eca8-11e7-91ca-9087af179bd1.png)
