### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by psoame** [ahonn/hexo-theme-even#34]
extends partial/layout include mixins/container include mixins/paginator block title title= config.title block container +home() block pagination +paginator('home')

**Comment by ahonn** [comment]
Have you installed plugin? And copy `_config.yml.sample` to `_config.yml`?

please run and try again:
```
$ npm install
$ npm install --save hexo-renderer-jade hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
$ cd  themes/even/
$ cp _config.yml.sample _config.yml
```

**Comment by gallonyin** [comment]
it helps me a lot thanks
