### ISSUE TITLE
字体渲染问题

### ISSUE THREAD

**Issue by xDidi3r** [ahonn/hexo-theme-even#35]
![pacman](http://ww4.sinaimg.cn/large/0060lm7Tgw1f731m1ibyzj30p209k3yz.jpg)
![even](http://ww1.sinaimg.cn/large/0060lm7Tgw1f731peib9rj30ho06oaa9.jpg)
上图为pacman主题 下图为even主题
为何字体渲染感觉差别很大

**Comment by xDidi3r** [comment]
图片可能看不太出。。。实际对比很明显even字体非常细

**Comment by ahonn** [comment]
是因为在 CSS 中使用了：

```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

不过这个字体渲染的区别只有在 Mac 下面看得出，Windows 下没有区别。
