### ISSUE TITLE
请问下更了主题css/style.css 404 问题

### ISSUE THREAD

**Issue by yangg** [ahonn/hexo-theme-even#36]
已经安装了 hexo-renderer-scss

**Comment by ahonn** [comment]
现在依旧 404？

**Comment by yangg** [comment]
发issue 更新后404

**Comment by yangg** [comment]
发issue 时更新后就404了

**Comment by yangg** [comment]
hexo g
之后，public/css里只有style.scss
而fonts文件夹里都是转换好的 css

**Comment by ahonn** [comment]
是否确保把 hexo-renderer-scss 安装在博客的根目录而不是主题的根目录？

这个看起来是 hexo-renderer-scss 没有启用，可能是安装到主题里了吧？

**Comment by yangg** [comment]
是在根目录，要不然，字体之类的也不会编译了

**Comment by ahonn** [comment]
font 的 css 不是 scss, hexo g 的时候直接移过去而已。
scss 文件在 hexo g 的过程中需要 hexo-renderer-scss 这个插件去渲染。

或许重新 hexo init, clone 主题试试？

**Comment by yangg** [comment]
Fixed, hexo 只加载 dependencies 里的插件，我装的时候用了 --save-dev。。。。
