### ISSUE TITLE
hexo server 输出 html 异常

### ISSUE THREAD

**Issue by yangg** [ahonn/hexo-theme-even#37]
```
(function() {
var d = document, s = d.createElement('script');

s.src = '//uedsky.disqus.com/embed.js';

s.setAttribute�@ɘk�S�>�>?Xɘs�><<8=�ɘ��A`;`;�;ʘ��~ . .H2 .ص�h˘����0�0�0�˘���
```

现在 其它正常了，但是hexo server页面底部的输出html类似这种，hexo g的结果没问题
每次刷新下面的乱码内容不一样。

**Comment by ahonn** [comment]
这个是 Hexo 的 Bug。hexo clean 一下再 hexo server 就好了。
只要 hexo g 没问题的话就可以 hexo d 上去了。

**Comment by yangg** [comment]
hexo clean 了也不行，
主要是 hexo server 写文章时刷新效果比较好，所以本地主要是用这种。

**Comment by ahonn** [comment]
这个有时候会出现有时候不会，而且也只在一个页面上出现。
所以我也不知道为什么会这样~一般都是在页面底部。

**Comment by yangg** [comment]
好的，谢谢！
其它页面没问题就可以，我一直在刷一个页面，以为所有页面会一样呢。
