### ISSUE TITLE
可否添加 mathjax 支持

### ISSUE THREAD

**Issue by zemora** [ahonn/hexo-theme-even#41]
你的主题很不错，风格很简洁，但是好像不支持数学公式，可以考虑加上这个功能吗？

**Comment by ahonn** [comment]
好的哟。这几天来给加上。感谢反馈~

**Comment by ahonn** [comment]
mathjax 的话好像可以直接使用插件，具体可以看这里 (Hexo MathJax插件)[http://catx.me/2014/03/09/hexo-mathjax-plugin/]。

所以我就不在主题里面加了，需要的话自行安装这个插件吧。

**Comment by quentin-chen** [comment]
这个插件不支持 jade 渲染方式，在你的主题上用不了啊……
