### ISSUE TITLE
Add LinkedIn as a social link

### ISSUE THREAD

**Issue by samjonester** [ahonn/hexo-theme-even#43]
Would it be possible to add LinkedIn as a social link? The only thing missing is the font. Not sure how those are generated, but here's LinkedIn's brand pack: https://brand.linkedin.com/downloads

**Comment by ahonn** [comment]
Hey, I've just add the Linkedln icon to the theme. You can update theme and use it.
For now, the social links icon haven't good custom solutions. If you have any solutions, please tell me ~
thanks for you feedback : )
