### ISSUE TITLE
生成失败

### ISSUE THREAD

**Issue by stdying** [ahonn/hexo-theme-even#45]
extends partial/layout include mixins/container include mixins/paginator block title title= config.title block container +home() block pagination +paginator('home')

**Comment by ahonn** [comment]
是否在博客根目录下执行了:
```
npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
```

**Comment by zzh2015** [comment]
get

**Comment by stdying** [comment]
好的,谢谢
