### ISSUE TITLE
Garbled code will be generated if .md file contains too many Chinese characters.

### ISSUE THREAD

**Issue by hokein** [ahonn/hexo-theme-even#46]
Firstly, thanks for your great work on this nice theme.

You can reproduce the issue with the following commands:

```
$ hexo init blog
$ cd blog
$ npm install
$ npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive
$ cd themes/
$ git clone https://github.com/ahonn/hexo-theme-even even
$ cd even/
$ cp _config.yml.sample _config.yml
// Change to your theme to `even`
```

And add [the md file](https://gist.github.com/hokein/10985513594b7856ba82c5b2709b4b48) to `source/_posts`, and run `hexo server` to see the generated page:

![image](https://cloud.githubusercontent.com/assets/2557445/18817604/3b15ad9a-8365-11e6-9df0-0f3329bf0607.png)

I'd suspect it is caused by the theme because it didn't happen when I changed to other theme. Could you help to take a look on it? Thanks! 

Environment:

```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.3.0
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

**Comment by nodejh** [comment]
+1 

![image](https://cloud.githubusercontent.com/assets/10287125/18906112/bfa7bf28-8598-11e6-8075-d3d4d5a4a8f0.png)

**Comment by nodejh** [comment]
后来又测试了，发现不是主题的问题，因为我使用 Hexo 默认的主题也会出现乱码。应该是 Hexo 本身的问题。

当中文和英文混杂，字符串长度超过1000左右的时候，就会出现乱码。

这个字符串乱码，估计是 Hexo 对中文编码处理的问题。我猜测，对于 Node.js 来说，如果中文是一个 Buffer 对象，比如 new Buffer('好').length ，则为 3，而 new Buffer('h').length 则长度为1，而 new Buffer('好').toString().length 为 1。所以可能是当中英文混合，字符串处理出问题了。

具体准确原因，尚不清楚。

**Comment by ahonn** [comment]
这个偶尔会出现，我也不知道是什么原因。不过只有 hexo s 的时候会出现，部署上去之后是没有问题的。所以也不知道有什么好的解决办法，我的文章都没那么长所以都没怎么遇到过。。。
不过还是很感谢那么细心的去测试，话说不用 hexo 的话用什么 jekyll 么？

**Comment by nodejh** [comment]
换成 hugo 了 [http://nodejh.com](http://nodejh.com)
