### ISSUE TITLE
文章末尾链接乱码

### ISSUE THREAD

**Issue by alonelyshepherd** [ahonn/hexo-theme-even#5]
在文章末尾我写了这些文字

- [Operator Overloading Considered Harmful](http://cafe.elharo.com/programming/operator-overloading-considered-harmful)
- [Operator Overloading Ad Absurdum](http://james-iry.blogspot.ru/2009/03/operator-overloading-ad-absurdum.html)
- [Why Everyone Hates Operator Overloading](http://blog.jooq.org/2014/02/10/why-everyone-hates-operator-overloading)

生成的html是这样的：

<li><a href="http://cafe.elharo.com/programming/operator-overloading-considered-harmful" target="_blank" rel="external">Operator Overloading Considered Harmful</a></li>
<li><a href="http://james-iry.blogspot.ru/2009/03/operator-overloading-ad-absurdum.html" target="_blank" rel="ex'A�0�*LM.52M).B'A�0����#M
-)V-1M.52M).R'A����#�
1# Z�2A�*08A�!*9*8M.9*8M
.'A�0�*LM.52M).'A�0�*LM.52M)."6�'A�0�*LM.52M).B'A�0����#M
-)V-1M.52M).#'A*8M
.'A�0�*LM.52M).&2A2M)./'����#!&MM*!6WM*-'A�0�*LM.52M).&2A2M)./'����#!&MM*!6aM*-'A�0�*LM.52M).'A�0�*LM.52M).P'����#���M!^l0#�M!^|5�߶#�P �F�F�F�F�F�F�F`�.new.targetH$����V�VPA�=�VPA�w�����PU�
xW X���H�H�CH�����H�� ��CH����CH��H��@���@����I�($
L9W�t$I�0$
L9W�tvalue�O�P
�`$

**Comment by ahonn** [comment]
@alonelyshepherd  应该是本地 server 这样子吧？我也遇到过，但是 deploy 之后是没有问题的。
