### ISSUE TITLE
Fancybox support ?

### ISSUE THREAD

**Issue by Bridouz** [ahonn/hexo-theme-even#51]
Hi,

I'm a true fan of your theme, it's clear and looks really great on any support.

However I have one missing feature, Fancybox support. It would be great if your theme supports jquery fancybox to render great galleries and images.

I will try to implement that feature and open a pull request if I managed to implement fancybox.

Have a good day,

**Comment by ahonn** [comment]
hey, guy

In the next few days, I will try to implement that feature.

Thank you for your feedback.

**Comment by yangg** [comment]
使用这个插件 https://github.com/m80126colin/hexo-tag-owl
owl local 可以直接实现 fancybox 的功能。
