### ISSUE TITLE
git pull后所有样式没有生效了

### ISSUE THREAD

**Issue by lepigs** [ahonn/hexo-theme-even#52]
很早之前用的  今天突然更新后所有样式全部失效？

**Comment by ahonn** [comment]
是否有安装 `hexo-renderer-scss` ？
样式文件现在是生成页面时编译的，所以需要安装这个。

**Comment by ahonn** [comment]
建议备份 blog 文章，然后重新 clone，按照 README 重新搞。
那样会避免一些不必要的修改。更新太多了，也不知道你具体是什么时候的版本。

**Comment by lepigs** [comment]
OK  谢谢
安装`hexo-renderer-scss`可以了
没怎么看Change Log  直接pull了
