### ISSUE TITLE
标签数量错误

### ISSUE THREAD

**Issue by Problem233** [ahonn/hexo-theme-even#55]
标签页统计的标签数与实际的标签数不符，实际只有2个标签，显示“A total of 4”

**Comment by Problem233** [comment]
经测试只有`hexo server`的时候才会出现这个情况，`hexo generate`不出现

**Comment by ensigma96** [comment]
试试hexo clean后再generate和server。问题是否仍存在？

**Comment by Problem233** [comment]
没问题了
