### ISSUE TITLE
几个功能增加的建议

### ISSUE THREAD

**Issue by quentin-chen** [ahonn/hexo-theme-even#58]
- [x] 浮动菜单栏：当页面滚动到下方的时候，菜单栏可以保持这样视觉效果会好很多。https://hyunseob.github.io 他的菜单栏很舒服。
- [x] 搜索框：建议在菜单栏上添加一下搜索框，文章多了有搜索还是很方便的。
- [x] ~~主页面层次：因为现在显示器都非常的宽，左右两边留白太多会太突兀，http://blog.daraw.cn 这个主题中的做法不错，把页面做成两个层次。~~

希望采纳回复，我自己有时间也去琢磨一下代码。

**Comment by ahonn** [comment]
- 浮动菜单栏一直有打算搞，后面有时间会先实现这个。
- 其实搜索框的话之前有尝试添加过，但是一直没有找到合适的位置去放搜索框。如果有好的建议，请告诉我~
- 主页面可能是不会改成那个主题那样，刚刚在浏览器里大概的试了一下，感觉与原来的风格不是很搭。我会尝试看看有没有更好的解决方案。

感谢你的反馈 : )

**Comment by quentin-chen** [comment]
不知道像这样弹出式的搜索框难度会不会太大：
http://appshopper.com

刚刚发现一个新的问题：
- [ ] 为什么只有Home页面的footer有社交链接图标，而其他页面没有？最重要的不应该是在每一篇post和about页面的底部放社交链接才是最重要的么？

**Comment by quentin-chen** [comment]
- [ ] prev next 标签预览

https://libhappy.com/2016/04/algs-4.5/
这位朋友的博客的preview 和 next 标签可以自动显示文章标签，感觉挺好的，你觉得如何？

**Comment by ahonn** [comment]
这两天在重构主题，加上了之前提到的浮动菜单栏与搜索框。

[feat: add mobile navbar](https://github.com/ahonn/hexo-theme-even/commit/d954ae024370802b11e3aba425cc02bbd6edd9fd)
![](http://ww3.sinaimg.cn/large/006tNc79gw1fan9itqe2kg30ac0iek6b.gif)

[feat: add search form in menu](https://github.com/ahonn/hexo-theme-even/commit/e59b7b2137dca8b084ab3fb42e6e7fbe02ac58b8)
![](http://ww2.sinaimg.cn/large/006tNc79gw1fan9evv4emg30n30afq3c.gif)

**Comment by quentin-chen** [comment]
这次重构  代码改动好大呀，自己的分支已经和你产生一大把 conflicts，看来我今晚也有得改了。
