### ISSUE TITLE
首页设置为只显示一篇文章时不会显示文章内容

### ISSUE THREAD

**Issue by hakale** [ahonn/hexo-theme-even#6]
当我这样设置且文章内不添加时，只会显示`阅读全文..`，不知道是不是缺省值设定，如果是的话，这样太奇怪了，不行实现想要的效果

**Comment by ahonn** [comment]
@hakale  首页的确是默认不显示详情的。。只显示一篇并且显示整一篇文章的话你可以在文章底部加 。这样应该就可以了..话说这需求好奇怪，这样首页不就变成文章页了..

**Comment by hakale** [comment]
@ahonn 因为首页显示多篇的时候没有的话就会显示全部内容，总有奇怪的需求嘛
