### ISSUE TITLE
logo displayed in *Comic Sans* before Chancery font is downloaded

### ISSUE THREAD

**Issue by ensigma96** [ahonn/hexo-theme-even#61]
The Chancery webfont is around 30KB and might take several hundred milliseconds to download (if it has not been cached, e.g. when people visit the site for the first time). Before that, the logo is displayed in Comic Sans on most Windows PCs (because of  `cursive` in the `font-family`).

![qq 20161114152916](https://cloud.githubusercontent.com/assets/12785341/20256648/c1b480f6-aa7f-11e6-983a-e23e8fb802d4.png)

**Comment by ensigma96** [comment]
Of course, it's just a minor problem, only bothering those who are *visiting the site for the first time* **and** *using a slow connection*.

**Comment by ahonn** [comment]
Temporarily no good solution. Chancery font is MacOS built-in font. On Windows/Linux, use cursive font when the font isn't downloaded. 

I can change to other font, but didn't find better. If you have any good idea, just tell me.
Thanks for you feedback.
