### ISSUE TITLE
希望可以import _setting.scss

### ISSUE THREAD

**Issue by xuzhao9** [ahonn/hexo-theme-even#65]
根据自己需要，可能需要修改一些css样式。source/css/_setting.scss可以被用来overwrite默认设置吗？（例如$global-body-width）希望可以在style.scss里面import setting这个设置文件，方便用户自定义css样式呀。

**Comment by ahonn** [comment]
_setting.scss 本来就是用来自定义某些样式的.. 由于我懒.. 一直没弄.. 有时间我尽快搞定它。
如果可以的话你可以修改完 PR 过来。

**Comment by xuzhao9** [comment]
已经提交PR

**Comment by ahonn** [comment]
更新了主题：
- 添加了 `bin/install` 脚本，复制配置文件与样式自定义文件，安装必要的 render 插件
- `_config.yml` 和 `css/_custom.scss` 现在会被忽略
- 主题只更新 `_config.sample.yml` 和 `css/_custom.sample.scss`，用户的主题配置与自定义样式不会被覆盖。

这样就解决了原先 import 时没有自定义样式的文件的问题了。主题样式中的所有可定义的变量都可以在 `source/scss/_costom.scss` 中自定义覆盖默认样式。

**Comment by xuzhao9** [comment]
我测试了一下，这样用安装脚本的方式就没问题了，感谢！
