### ISSUE TITLE
移动端显示问题

### ISSUE THREAD

**Issue by Leonard-Peng** [ahonn/hexo-theme-even#67]
在手机浏览博客首页时，如图所示，第一篇文章的标题会与导航栏部分重叠。猜测是因为 title 太长，占据了两行？
![screenshot_20161128-180349_01](https://cloud.githubusercontent.com/assets/9429885/20664229/41dabe24-b595-11e6-9670-82994f94b20b.png)

**Comment by Leonard-Peng** [comment]
测试了一下，修改了 `<ul class="home">`的`margin-top`后显示正常。 很喜欢这个主题，希望能根据 title 的长度动态调整^_^
![image](https://cloud.githubusercontent.com/assets/9429885/20664369/dc5feef6-b595-11e6-99c5-e47dfebd6c7b.png)

**Comment by ahonn** [comment]
感谢反馈~ 长度动态调整有空我去加上。
其实是不推荐那么长的博客名称的，也不建议中英文混合，不好看。 直接 Leonard Peng 会不会比较好。

**Comment by Leonard-Peng** [comment]
的确，直接修改为短 Title 是最快的解决方法😂
