### ISSUE TITLE
首页图片不显示

### ISSUE THREAD

**Issue by sshuair** [ahonn/hexo-theme-even#68]
在之前的文章，在首页里面不显示，点进文章中才会显示

**Comment by ahonn** [comment]
https://github.com/ahonn/hexo-theme-even/blob/master/doc/doc_zh.md#%E4%BF%AE%E6%94%B9%E9%A6%96%E9%A1%B5%E6%96%87%E7%AB%A0%E9%A2%84%E8%A7%88%E4%BD%8D%E7%BD%AE

**Comment by sshuair** [comment]
你看这个图片就没有显示
<img width="797" alt="2016-12-01 10 11 10" src="https://cloud.githubusercontent.com/assets/5787131/20779323/c8df539c-b7ae-11e6-988e-53a265b0c4ca.png">

**Comment by ahonn** [comment]
http://notes.sshuair.com/beijing_3360x2100.png  这个地址 404 啊，确定图片的地址没错？

**Comment by sshuair** [comment]
没有啊，http://notes.sshuair.com/2016/11/30/maps/road2rome/，你看文章里面是可以显示的，但是到首页就没法显示了。

**Comment by ahonn** [comment]
噢.. 我明白了。图片与文章是放在同一个目录？这个是路径的问题，所以在首页上根本找不到这个图片。
建议在 `source/images` 内放置图片资源，这样在任何页面都可以用 `/images/xxxx.png` 获取到图片。
或者是把图片放在七牛之类的图床。

**Comment by sshuair** [comment]
soga，不过这样写起来会麻烦一点，组织结构也有点乱，多谢多谢，手动抱拳

**Comment by ahonn** [comment]
图片放到本地的话的确是比较麻烦，所以我大多直接丢七牛。那样加载起来的速度也会快一点。 😀
