### ISSUE TITLE
Next、Prev逻辑问题

### ISSUE THREAD

**Issue by sshuair** [ahonn/hexo-theme-even#69]
按照习惯，Next不应该是显示当前文章发布时间之后的最新文章吗，而Prev打开的应该是老的文章，现在的逻辑关系似乎颠倒了啊。

**Comment by ahonn** [comment]
不啊。Prev 是上一篇文章，所以是比当前文章更新的文章啊。
如果按照那样的逻辑，两个按钮的位置似乎应该换过来，那样更不符合逻辑了啊..

**Comment by sshuair** [comment]
反正我之前看到的逻辑与你这个都是反的，你看[http://mindhacks.cn/](http://mindhacks.cn/)，还有按照人的操作习惯，比如看书，都是右下角的是最新的文章。现在的设置总是感觉怪怪的，仅供参考😄

**Comment by ahonn** [comment]
或许修改成 Newer 和  Older 会更好？然后按照操作习惯把最新的文章放到右边？

**Comment by sshuair** [comment]
恩，这个办法好，不会产生歧义。

**Comment by ahonn** [comment]
不过这里有个问题，就是其他语言的话也需要找到合适的词，例如中文就不知道用什么好了。

**Comment by sshuair** [comment]
newer：下一篇， older：上一篇。要不就直接放前一篇、后一篇的标题？

**Comment by quentin-chen** [comment]
我觉得两种说法都说得通，逻辑上都没有什么问题。通常情况下，其实阅读者都不在乎上一篇，下一篇到底映射的是时间顺序的还是倒序的。关键是当有系列文章出现的时候，下一篇最好是要映射到系列增序的文章上去。而增序文章一般也是时间顺序的，也就是说，（一）的「next」（二）应该是更新的一篇文章才好。

从这样看来，next 对应时间更新的文章更妥帖一点。

以上。

**Comment by ahonn** [comment]
其实这是根据 Hexo 文档中的[变量](https://hexo.io/zh-cn/docs/variables.html#页面变量)的逻辑来的。

昨天试着改了，感觉怪怪的（可能是由于习惯了原来的逻辑）。所以暂时不会对这个逻辑进行更改。有需要的话可以自行更改 `layout/mixins/paginator.jade`。

直接改成前后文章的标题也有考虑过，感觉太长了..
