### ISSUE TITLE
markdown列表功能无效

### ISSUE THREAD

**Issue by kpskp77** [ahonn/hexo-theme-even#7]
markdown的未排序列表好像没有效果，试了`-`， `+`，`*`都没用。。。

**Comment by ahonn** [comment]
@kpskp77 使用其他主题的时候是正常的吗？

**Comment by kpskp77** [comment]
默认的landscape是正常的

**Comment by ahonn** [comment]
@kpskp77  突然意识到是我去掉了无序列表的 style，已修复

**Comment by kpskp77** [comment]
@ahonn 已更新。主题很简洁，很喜欢。谢谢你的工作。

**Comment by ahonn** [comment]
@kpskp77 感谢支持~有什么建议可以给我反馈反馈哦。我可以求个 star 吗~哈哈哈
