### ISSUE TITLE
generate style.css failed 

### ISSUE THREAD

**Issue by quentin-chen** [ahonn/hexo-theme-even#70]
```
Error: File to import not found or unreadable: custom
Parent style sheet: .../even/source/css/style.scss
ERROR Asset render failed: css/style.css
Error: File to import not found or unreadable: custom
Parent style sheet: .../even/source/css/style.scss
    at options.error (.../node_modules/node-sass/lib/index.js:292:26)
```

**Comment by ahonn** [comment]
New  feature: custom theme styling.
Run `bin/install`(Need back up `_config.yml`, will cover) or create `source/css/_custom.scss` fix this problem(The sample files: `source/css/_custom.sample.scss`).

**Comment by quentin-chen** [comment]
Yes, I got it just now, and created the custom.scss by my self.
You'd better update the instruction if you haven't~
