### ISSUE TITLE
Code font size

### ISSUE THREAD

**Issue by quentin-chen** [ahonn/hexo-theme-even#71]
修改 `$code-font-size: 13px;` 到 `$code-font-size: 15px;` 之后，代码块的显示出现问题。
因为我调大到了正文字号，如果 code 字号保持不变的话，有些不协调，可是调大之后略有问题。

**Comment by ahonn** [comment]
这是之前写的时候没有考虑欠佳。因为生成的代码中有空行的话是没有高度的（line-height 不管用，只能直接设置 height），就莫名的少了一行导致显示错误。所以比较暴力的直接给固定高度，改变代码字体大小的时候行高依旧是固定的，就导致代码块行号与代码内容高度不一致。现在修复了，行高根据字体大小变化。

**Comment by quentin-chen** [comment]
嗯，Rebase 之后已经好了！很效率~
