### ISSUE TITLE
保持页面底部样式一致

### ISSUE THREAD

**Issue by alexwan2011** [ahonn/hexo-theme-even#73]
hi你好，添加Tags和Archives以及其它自定义页面以后，底部的样式和Home底部的样式都不太统一，有的什么内容都没有，有的没有social link，请问可以自己修改成样式全部和Home一样吗？谢谢:)

**Comment by ahonn** [comment]
是这样的，由于 tags 与 categories 页一般会比较短，所以我就把 footer 去掉了。刚刚修改了一下，除了  tags 与 categories 页的其他页面都会显示 social link 和 copyright。

如果有需要的话，可以自行修改 `layout/partial/footer.jade`

**Comment by alexwan2011** [comment]
好的，谢谢！
