### ISSUE TITLE
文章尾部部分显示乱码问题

### ISSUE THREAD

**Issue by BigmingTalk** [ahonn/hexo-theme-even#75]
大家好，我很喜欢even这个主题，但在我生成文章的是后，总是会有一些文章的末尾出现乱码（我之前用其他主题没有问题）。我已经将markdown文件都用utf-8保存了，不知道大家是否有遇到过类似问题？谢谢。

**Comment by ahonn** [comment]
查看 https://github.com/ahonn/hexo-theme-even/issues/46
