### ISSUE TITLE
如何添加disqus？

### ISSUE THREAD

**Issue by jingsam** [ahonn/hexo-theme-even#78]
如何添加disqus？文档中似乎没有相应的说明

**Comment by ahonn** [comment]
文档忘记写了。在这里 [添加评论服务](https://github.com/ahonn/hexo-theme-even/wiki/%E6%B7%BB%E5%8A%A0%E8%AF%84%E8%AE%BA%E6%9C%8D%E5%8A%A1)

**Comment by jingsam** [comment]
多谢
