### ISSUE TITLE
[功能建议]能不能将社交链接配置到更显眼的位置？

### ISSUE THREAD

**Issue by jingsam** [ahonn/hexo-theme-even#80]
![image](https://cloud.githubusercontent.com/assets/1522494/21142620/0be3dd1a-c17e-11e6-91bc-bb3d81fb1c68.png)
默认的社交链接在页面底部，太难找了，能不能配置到更显眼的位置呢？比如顶部

**Comment by ahonn** [comment]
顶部的话并没有位置好放啊

**Comment by jerry011235** [comment]
建议1：
![2016-12-27_165648](https://cloud.githubusercontent.com/assets/12509976/21496112/fab6ba60-cc56-11e6-9299-5dde8d6e9fe2.png)
建议2：
![2016-12-27_1656481](https://cloud.githubusercontent.com/assets/12509976/21496113/fc3432d2-cc56-11e6-92d8-2ba009cec2af.png)
手机端可以仿照[landscape-plus](https://github.com/xiangming/landscape-plus)
![gif](https://cloud.githubusercontent.com/assets/12509976/21496123/14b53f4a-cc57-11e6-8c1a-af12d3e52655.gif)
