### ISSUE TITLE
更改首页的文章数

### ISSUE THREAD

**Issue by jingsam** [ahonn/hexo-theme-even#81]
现在首页和归档都是显示10篇文章，我觉得首页显示的文章太多了，能不能配置首页只显示一两篇文章，而归档按10分页？

**Comment by ahonn** [comment]
在站点的配置文件中能够设置：

```
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
```

**Comment by ahonn** [comment]
单独控制 archive 或者 tags 等页面的每页文章数可以使用 `hexo-generator-archive`，`hexo-generator-tags` 插件提供的配置。

**Comment by jingsam** [comment]
3ks
