### ISSUE TITLE
搜索好像只能搜索标题

### ISSUE THREAD

**Issue by entron** [ahonn/hexo-theme-even#82]
好像不能搜索正文。

**Comment by ahonn** [comment]
原来是可以的.. 我去掉了而已。看来还是加上比较好。

**Comment by entron** [comment]
跟新了主题，不过现在在搜索栏输入任何东西都没有反应。

**Comment by ahonn** [comment]
测试了没有问题啊。`hexo g` 之后 `public` 文件夹里面是否存在 `search.xml` ?
没有的话需要重新安装一下 `hexo-generator-search`

**Comment by entron** [comment]
生成了`search.xml`。不知道为啥输入框输入啥都没反应，也不说搜到也不说搜不到。会不会是javascript的错误？
