### ISSUE TITLE
更新后社交链接似乎不见了

### ISSUE THREAD

**Issue by jingsam** [ahonn/hexo-theme-even#83]

**Comment by ahonn** [comment]
这个部分我并没有改动，请检查配置文件。

**Comment by jingsam** [comment]
http://www.ahonn.me/2016/12/13/2016-summary/
你自己的页面都没有了
![image](https://cloud.githubusercontent.com/assets/1522494/21217333/a164b2ec-c2e6-11e6-9f89-e5ef096e07eb.png)

**Comment by ahonn** [comment]
![](http://ww4.sinaimg.cn/large/006tNc79gw1farluhmhnrj30ik0423yj.jpg)

我这边看到的是这样.. 换个浏览器试试？或许需要清除一下缓存
