### ISSUE TITLE
请问怎么将左上角顶部的Hexo改为类似README中展示的Even？

### ISSUE THREAD

**Issue by alpsem** [ahonn/hexo-theme-even#84]
就像http://www.ahonn.me中一样，左上角文字是自定义成ahonn而不是默认的hexo。

而底部的copyright部分也是自定成© 2015 - 2016  Ahonn，而不是默认的John Doe。请问这是怎么做到的？

**Comment by ahonn** [comment]
修改站点根目录下的 _config.yml 文件中的 title 字段。
