### ISSUE TITLE
请问even主题怎样修改font-family？

### ISSUE THREAD

**Issue by alpsem** [ahonn/hexo-theme-even#85]
默认的font-family: "Source Sans Pro", "Helvetica Neue", Arial, sans-serif;字体效果不是很好，想自己重新定义一样，请问应该怎么做？

**Comment by ahonn** [comment]
几乎所有的样式变量都在 `source/css/_variables.scss` 中，你可以在 `source/css/_custom/_custom.scss` 中添加同名样式变量自定义。（格式与 `_variables.scss` 中相同，但不包含 `!default`）

**Comment by alpsem** [comment]
@ahonn 通过修改 $global-font-family成功修改了body的字体，但是对于标题不知道应该修改哪里。
```
.post .post-header .post-title {
    margin: 0;
    font-size: 27px;
    font-weight: 200;
    font-family: Athelas, STHeiti, Microsoft Yahei, serif;
}
```
在source/css/_variables.scss好像并没有找出相关的变量，能不能具体指出应该修改哪一个变量？

**Comment by alpsem** [comment]
@ahonn 问题已经解决，同样修改$global-serif-font-family，谢谢作者的回答。
