### ISSUE TITLE
分类页面能否渲染成竖排格式？

### ISSUE THREAD

**Issue by jerry011235** [ahonn/hexo-theme-even#87]
分类页面能否渲染成竖排格式，这样一级分类和二级分类显得条理清晰些。
![2016-12-27_173636](https://cloud.githubusercontent.com/assets/12509976/21496742/9efe3d38-cc5b-11e6-8c9f-a5b7d8c6fe18.png)

**Comment by ahonn** [comment]
对页面布局的大改动目前都不会考虑
