### ISSUE TITLE
【bug】首页出现多篇重复文章

### ISSUE THREAD

**Issue by jerry011235** [ahonn/hexo-theme-even#88]
`hexo s`后，发现首页有很多重复的文章，但是`source\_posts`里的文章确实是每篇不同的。
重装hexo后发现也有这个问题。

**Comment by ahonn** [comment]
可否贴出具体的log？这样我无法得知什么问题。hexo clean 之后依旧？






-------- 原始邮件 --------
发件人：starship <notifications@github.com>
时间：周二 12月27日 18:21
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[ahonn/hexo-theme-even] 【bug】首页出现多篇重复文章 (#88)


hexo s后，发现首页有很多重复的文章，但是source\_posts里的文章确实是每篇不同的。
重装hexo后发现也有这个问题。

**Comment by jerry011235** [comment]
[http://starwindy.oschina.io/](http://starwindy.oschina.io/)
这是`hexo clean && hexo g && hexo d `之后形成的。
log在[这里](https://github.com/jerry011235/test/blob/master/777/debug.log)，看起来似乎一切正常。
我的hexo在 `D:\hexo\hexo `，路径太深有无影响？还是md文件太多的原因？

**Comment by lineng11** [comment]
这个Bug我也遇到了
重现: 
A(12-31)文章加    
B(12-30)文章不加 全部显示
然后发现 B也成了A简要，只是显示重复

**Comment by ahonn** [comment]
我这边无法复现，看了好久代码.. 没发现有错误的地方。

@jerry011235  我看到你的博客现在显示正常了？
@lineng11  多次 `hexo clean` 之后还是出现相同的状况吗？

**Comment by jerry011235** [comment]
@ahonn 依旧没有，问题估计和[! more  问题](https://github.com/ahonn/hexo-theme-even/issues/93)类似，难道是node版本？我的是node: 6.9.2
我的 hexo -v 
```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.7.0
node: 6.9.2
v8: 5.1.281.88
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

**Comment by ahonn** [comment]
@jerry011235  一脸懵逼，估计得等到放假才有时间去搞。 最近考试什么的而且还有大作业没搞定。

**Comment by jerry011235** [comment]
@ahonn 不急，先忙你自己重要的事吧。再次感谢。
