### ISSUE TITLE
开启站内搜索 点击后跳转 错误

### ISSUE THREAD

**Issue by luhaoaimama1** [ahonn/hexo-theme-even#89]
http://ww38.yoursite.com/2016/12/28/index的副本%203/

**Comment by luhaoaimama1** [comment]
http://ww38.yoursite.com/2016/12/28/index的副本%203/

**Comment by lineng11** [comment]
根目录下面_config.yml   url:换成自己线上地址

**Comment by lineng11** [comment]
根目录下面_config.yml   url:换成自己线上地址

**Comment by luhaoaimama1** [comment]
超级感谢~ Like you！
