### ISSUE TITLE
about.jade的问题

### ISSUE THREAD

**Issue by owen05** [ahonn/hexo-theme-even#9]
您好~我想问下，我修改您的about.jade文件，为啥没有变化呢，其他所有的文件都可以。。。。

**Comment by ahonn** [comment]
阿嘞，怎么 close 了。不是很明白你说的意思

**Comment by owen05** [comment]
我刚开始学hexo。。。。就没好意思再问了。。。。

大体意思就是我修改about.jade那个文件，希望把评论的block去掉，但是删除后，怎么generator都不行。。。。。其他的jade文件比如index.jade就可以随意改，都会起变化。。。是不是about那个页面没有通过生成，而是写死的呀。。。。。。

**Comment by ahonn** [comment]
不知道你这是什么状况，不过我刚刚已经添加了评论的开关了。可以更新一下。

在主题的配置文件的 comments 项下设置，具体我已经更新到文档了。

感谢支持~
On May 24, 2016, at 16:22, owen05 <notifications@github.com<mailto:notifications@github.com>> wrote:

我刚开始学hexo。。。。就没好意思再问了。。。。

大体意思就是我修改about.jade那个文件，希望把评论的block去掉，但是删除后，怎么generator都不行。。。。。其他的jade文件比如index.jade就可以随意改，都会起变化。。。是不是about那个页面没有通过生成，而是写死的呀。。。。。。

**Comment by owen05** [comment]
好的好的~，还发现个问题哈，就是script.jade那个文件，发现目前二级目录以下的页面引不到js滴，改成script(src=url_for("js/back2top.js"))就好使啦~，你可以看看。post.jade那个文件，好像重复引进了post()方法，导致点击进入具体博客里会出现double的情况，你可以一并看下啦~


我也是刚开始弄，有啥问题随时请教你哈，多谢啦！
> 在 2016年5月24日，下午4:42，Yuexun <notifications@github.com> 写道：
> 
> 不知道你这是什么状况，不过我刚刚已经添加了评论的开关了。可以更新一下。 
> 
> 在主题的配置文件的 comments 项下设置，具体我已经更新到文档了。 
> 
> 感谢支持~

**Comment by ahonn** [comment]
刚刚看了一下，是前几天改的时候不小心搞错的，昨天我还纳闷呢。正在 debug 呢，等一下就 push 上去。感谢反馈。

**Comment by owen05** [comment]
好的，还有一个问题哈。。。。。。。标签那个页面，底下的标签字体大小是随机的吧？但不是很明白你的这个方法额。。。。实际的效果一直是14px大小的。。。。想问下你是在哪里实现随机赋予文字大小的逻辑的呀？。。。还是这块儿是个小bug呢？

**Comment by ahonn** [comment]
这个是 hexo 自带的 helper 函数 [tagcloud](https://hexo.io/docs/helpers.html#tagcloud)

字体的大小是根据有标签的文章的数量

**Comment by owen05** [comment]
这样呀~。。。。好的好的，多谢！

**Comment by ahonn** [comment]
OK，现在应该已经把已知的问题搞定了。

**Comment by owen05** [comment]
好的~那个移动端没有侧边栏嘛~还是特意隐掉的呀？

**Comment by ahonn** [comment]
没有侧边栏，移动端没写呢

**Comment by owen05** [comment]
哈哈，好吧，你大二嘛，挺厉害滴~向你学习啦~
