### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by luhaoaimama1** [ahonn/hexo-theme-even#90]
* 添加置顶功能
* 搜索 hint提醒 
     >毕竟 搜索他们可能都不知道是不是站内搜索

**Comment by Wilbeibi** [comment]
现在搜索貌似没有了，po 主有计划加回来么？

**Comment by LIUYOU2015** [comment]
想要搜索功能+1

**Comment by loremwalker** [comment]
建议增加头像、像next主题一样有图片模式以及左右的相关侧边栏显示、友链、日历插件等功能，我觉得像这样修改过的even主题可能更受欢迎，显示也不失精简大气，至于它的顶部设置，我倒觉得还不如even默认好看
![](http://p4.cdn.img9.top/ipfs/QmV5Ff971XFZKCfPCfSU8HWdWYzUyaq7zTUBqm6Az2Ww1K?4.png)

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： https://github.com/hexojs/hexo-generator-index/pull/51
