### ISSUE TITLE
导航问题

### ISSUE THREAD

**Issue by luhaoaimama1** [ahonn/hexo-theme-even#91]
* 当导航长度超出页面高度的时候  下拉也到不了最后啊 

* 而且排版 有的会多出空行
[关于导航之我的博客](https://luhaoaimama1.github.io/2016/12/28/hexo/)

**Comment by luhaoaimama1** [comment]
[.md 文件 ](https://github.com/luhaoaimama1/Github_IO_Posts/blob/master/_posts/hexo.md)
>刚刚发给你邮箱了 但是我发现这样更有效，即使丢失电脑也不怕了哈哈

**Comment by ahonn** [comment]
很抱歉现在才回复。
关于文章目录会出现空行，是因为你直接从 h2 跳到了 h4。
