### ISSUE TITLE
<!-- more --> 问题

### ISSUE THREAD

**Issue by JoakimLiu** [ahonn/hexo-theme-even#93]
你好，感谢你写出这么让人舒服的hexo主题，我按照 wiki 操作过程中，发现添加了  没有作用，还是每篇文字全部都显示出来，并且文章标题也没法点击，只能在 archives 中查看，我之前是用的 landscape-plus 主题，麻烦帮忙解决一些，谢谢！

**Comment by JoakimLiu** [comment]
附上我的blog链接 http://joakimliu.github.io/，貌似要翻墙才能访问，以前不翻墙都能直接访问的。(⊙o⊙)…

**Comment by JoakimLiu** [comment]
附上我的博客链接：http://joakimliu.github.io/

要翻墙才能访问，以前不翻墙都能访问的。

**Comment by ahonn** [comment]
看起来像是 `is_home()` 这个函数返回的值不是预期的.. 这就很奇怪了。
`hexo clean` 之后还是这样吗？ 能否提供 md 文件？

**Comment by JoakimLiu** [comment]
嗯，clean 还是一样的，md文件发你邮件了。

**Comment by JoakimLiu** [comment]
就是你博客底部的邮件。

**Comment by ahonn** [comment]
我这边依旧无法复现.. 无法得知原因.. 我重新 hexo init 之后 clone 主题，放入你的 md 文件显示是正常的。

`hexo -v` 显示的版本的多少？
这是我这边的版本，也许跟 hexo 版本有关：
```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 16.3.0 darwin x64
http_parser: 2.7.0
node: 6.6.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

**Comment by JoakimLiu** [comment]
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.2.2
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
