### ISSUE TITLE
请问如何设置title和menu分别左右对齐？

### ISSUE THREAD

**Issue by zhanghedr** [ahonn/hexo-theme-even#94]
觉得主题做的很好看，从next转过来了，不过请假一个问题，默认情况下首页顶部的title和menu不是和内容左右对齐的，请问如何设置修改可以让他们俩左右对齐内容，像这个blog一样：https://funhacks.net/

谢谢

**Comment by ahonn** [comment]
主题的大部分样式都可以通过 `_custom.scss` 来自定义。
可以在 `_custom.scss` 中添加 `$header-padding: 20px 0;` 达到上述效果。
感谢你的使用~

**Comment by zhanghedr** [comment]
这样就好了，谢谢
