### ISSUE TITLE
建议在wiki中加设置语言介绍

### ISSUE THREAD

**Issue by zhanghedr** [ahonn/hexo-theme-even#95]
因为每种主题语言key的value可能不同，even的应该是en和zh-cn吧，建议在wiki中加一个设置语言的介绍，比如在_config.yml中修改language: zh-cn。

**Comment by ahonn** [comment]
感谢建议。已经在 wiki 中添加了 [设置站点语言](https://github.com/ahonn/hexo-theme-even/wiki/%E8%AE%BE%E7%BD%AE%E7%AB%99%E7%82%B9%E8%AF%AD%E8%A8%80)。
